### ISSUE TITLE
DOTA Dataset

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#1]
https://captain-whu.github.io/DOTA/index.html

DOTA is a large-scale dataset for object detection in aerial images. It can be used to develop and evaluate object detectors in aerial images. The images are collected from different sensors and platforms. Each image is of the size in the range from 800 × 800 to 20,000 × 20,000 pixels and contains objects exhibiting a wide variety of scales, orientations, and shapes.

**Comment by adamjstewart** [comment]
Closing this because it isn't really an issue. Someone can add this dataset at any time if they want to. I don't think we need an issue to track progress on this dataset because there is no work in progress.

**Comment by calebrob6** [comment]
Should we have an overall dataset tracking issues?

**Comment by adamjstewart** [comment]
I'm not sure if that's necessary. Since there are infinitely many datasets we could add, that kind of issue would never be closed. Also, only maintainers would be able to add datasets to that list.
