### ISSUE TITLE
torchrs

### ISSUE THREAD

**Issue by isaaccorley** [microsoft/torchgeo#104]
Seems like we had very similar ideas for creating a pytorch based torchvision like library for remote sensing (see [torchrs](https://github.com/isaaccorley/torchrs)).

I want to gauge the interest for consolidating the datasets and models from torchrs into torchgeo. I would be happy to submit PRs for this but want to know your thoughts.

**Comment by calebrob6** [comment]
Indeed! I saw torchrs a few days ago -- looks awesome by the way! -- when the PyTorch Lightning folks tweeted about it and had noted down to reach out to you about this after we hit the "public" button. It would be great to collaborate on this moving forward.

It looks like most of the datasets you've implemented could be [VisionDatasets](https://github.com/microsoft/torchgeo/blob/c63fa688db267b39eeb6da6f25e721b96d3eef69/torchgeo/datasets/geo.py#L543) without much trouble, then we could worry later about converting relevant ones to GeoDatasets. @adamjstewart, thoughts?

**Comment by adamjstewart** [comment]
Yes, that would be fantastic! So far we've been more concerned with CI/documentation and sampling/benchmarking and haven't gotten a chance to implement as many datasets as torchrs has. I would love to combine forces and make an awesome library for deep learning in remote sensing!

**Comment by isaaccorley** [comment]
Great! I'll start looking through the codebase and make a PR for one of the simpler datasets to start with.

There are a few other unique datasets (image captioning, visual question answering, and audio visual recognition) that may need some more thinking through though.
