### ISSUE TITLE
EuroSAT Dataset URL not being secure anymore

### ISSUE THREAD

**Issue by julien-blanchon** [microsoft/torchgeo#1064]
### Description

As `url = "https://madm.dfki.de/files/sentinel/EuroSATallBands.zip"` is not secure anymore, downloading the EuroSat dataset is blocked by default by certify.

We might need to either change the zip source or remove the `https`

### Steps to reproduce

Load the EuroSAT dataset
```python
from torchgeo.datasets import EuroSAT
eurosat_train = EuroSAT(download=True)
```

### Version

0.4.0

**Comment by julien-blanchon** [comment]
https://github.com/microsoft/torchgeo/pull/1065

**Comment by calebrob6** [comment]
Thanks @julien-blanchon -- we opened an issue in the EuroSAT repo last week (https://github.com/phelber/EuroSAT/issues/10) and were hoping that they fix the expired certificate ASAP. It looks like we will need to switch to http though.
