### ISSUE TITLE
Add "Launch in Hub" button to tutorials

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#117]
We currently have a "Open in Colab" button for our tutorials. We should also have one for the Planetary Computer. See https://planetarycomputer.microsoft.com/dataset/landsat-8-c2-l2#Example-Notebook for an example of how this works.

**Comment by adamjstewart** [comment]
I think the URL exists to make this work, but I don't think there's a nice button to display like with "Open in Colab".

**Comment by adamjstewart** [comment]
@calebrob6 can you get in touch with the Planetary Computer folks and ask if this is a feature they support for external repos? The URL seems to hardcode the compute location and I don't see a button available. The URL is also kinda long...

https://pccompute.westeurope.cloudapp.azure.com/compute/hub/login?next=%2Fcompute%2Fhub%2Fuser-redirect%2Fgit-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fmicrosoft%252FPlanetaryComputerExamples%26urlpath%3Dlab%252Fworkspaces%252Flandsat-8-c2-l2-landsat-8-c2-l2-example%252Ftree%252FPlanetaryComputerExamples%252Fdatasets%252Flandsat-8-c2-l2%252Flandsat-8-c2-l2-example.ipynb%26branch%3Dmain

I'm fine with only advertising Google Colab. Just figured Azure/Planetary Computer might like some free advertising too.

**Comment by calebrob6** [comment]
@TomAugspurger, does the Planetary Computer support a "Launch in Hub" button for external scripts? We'd like to add this button on our tutorial notebooks (e.g. https://torchgeo.readthedocs.io/en/stable/tutorials/getting_started.html).

**Comment by TomAugspurger** [comment]
You can use https://jupyterhub.github.io/nbgitpuller/link to generate links for any Hub that has nbgitpuller installed. So I think you want something like https://pccompute.westeurope.cloudapp.azure.com/compute/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ftorchgeo%2F&urlpath=lab%2Ftree%2F%2Fdocs%2Ftutorials%2Fgetting_started.ipynb&branch=main. I've noticed occasional issues with jupyterhub / the notebook server getting a bit confused, possible with running sessions. So the links from our catalog (e.g. https://planetarycomputer.microsoft.com/dataset/sentinel-2-l2a#Example-Notebook) also include a urlencoded "workspace" parameter: https://pccompute.westeurope.cloudapp.azure.com/compute/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FPlanetaryComputerExamples&urlpath=lab%2Fworkspaces%2Fsentinel-2-l2a-sentinel-2-l2a-example%2Ftree%2FPlanetaryComputerExamples%2Fdatasets%2Fsentinel-2-l2a%2Fsentinel-2-l2a-example.ipynb&branch=main

One note: gitpuller doesn't currently understand "profiles", so you'll need to tell users to select the "GPU - pytorch" profile (https://github.com/jupyterhub/nbgitpuller/issues/68)

**Comment by calebrob6** [comment]
Thanks Tom! 

Question re the workspace parameter:

It looks like this is encoded in the "urlpath" parameter: `lab/workspaces/<some workspace name>/tree/<path/to/file.ipynb>` vs. what you get from nbgitpuller `lab/tree/<path/to/file.ipynb>`. Is this correct? If so, can `<some workspace name>` be anything, or does it have to exist on the hub server already (I see that the workspace names in the PC example URLs are specific workspace names unique to each notebook)

**Comment by TomAugspurger** [comment]
Anything unique should work.

**Comment by calebrob6** [comment]
Great, thanks again!

**Comment by adamjstewart** [comment]
I think we can use https://shields.io/ to create a badge

**Comment by adamjstewart** [comment]
Note that since the URL contains the "main" branch, it will suffer from the same problem as https://github.com/microsoft/torchgeo/issues/274#issuecomment-996230425. Still trying to figure this out, but no reason we can't add a badge with the same issues as Google Colab.

**Comment by adamjstewart** [comment]
Got this working, will open a PR once #309 is merged.
