### ISSUE TITLE
Bounding box is invalid Error

### ISSUE THREAD

**Issue by TolgaAktas** [microsoft/torchgeo#1175]
### Description

I am taking the intersection of the two Landsat8 datasets that have different root paths. One is for the shadow-free images and the other one for the shadowed images.  I am getting the following error message although my images are limited to one WRS path row location for the minimally viable testing. 

I have the following code but I am getting the error at sampler stage. 

<img width="830" alt="image" src="https://user-images.githubusercontent.com/15706155/224911482-e6d14267-c2a6-463c-ac58-68252cdf424c.png">

Here's the error message

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/15706155/224911323-4c3fb7b5-f843-41f2-a44f-dde5db02b4eb.png">

### Steps to reproduce

1. I have downloaded the Landsat8 products for path = 16 & row = 30 at multiple dates. I moved the images with 0 - 2 % cloud cover ratio to a clean_image directory and moved the others (10 - 40% cover) to a shadowimage directory. 
2. I instantiated Landsat8 objects using these rootpaths, and defined bands as 
bands = ["B1","B2","B3","B4","B5","B6","B7","B8","B9","B10", "B11","QA_PIXEL"]

3. I take the intersection of two datasets that are from the same area but having different cloud cover ratios. 
4. At this point the sampler on the dataset would have

### Version

0.3.1

**Comment by TolgaAktas** [comment]
More information about the datasets:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/15706155/224912348-12604281-3031-4fe9-8eaf-c0ff15804d4b.png">

**Comment by adamjstewart** [comment]
Can you print `all_set` too? I suspect that it has size 0, that is, that there are no images between the two sets that overlap. Although you may have multiple images from the same location, if they aren't from the same time, then they have no overlap. If you want to ignore the time dimension, you would need to modify [these lines](https://github.com/microsoft/torchgeo/blob/v0.4.0/torchgeo/datasets/utils.py#L349,L350) from:
```python
max(self.mint, other.mint),
min(self.maxt, other.maxt),
```
to:
```python
min(self.mint, other.mint),
max(self.maxt, other.maxt),
```

**Comment by TolgaAktas** [comment]
You are right, trying to print the datasets produces the same error message. But the creating IntersectionDataset silently fails without any errors. When you say they have to be from the same time, is literally the same date and time? That would be impossible to match, but I rather need them to be from the same area and it's OK if it's different times. 

![image](https://user-images.githubusercontent.com/15706155/225074592-5e656bef-ee63-4b20-9115-58b06c9d1001.png)

**Comment by adamjstewart** [comment]
Yes, if the images have temporal resolution down to the second, then they would need to have a matching second to be considered intersecting. If the images don't have any temporal component or it's at the year resolution, then things would be easier.

Actually, an easier hack to get what you want would be:
```python
from torchgeo.datasets import Landsat8

Landsat8.filename_regex = "_(?P<band>[A-Z0-9_]+)\."

clean_set = ...
noisy_set = ...
```
This removes the `date` part of the regex so that TorchGeo assumes there isn't any way to know the datetime at which an image was taken and instead only considers spatial intersection.

**Comment by TolgaAktas** [comment]
That's indeed a good workaround, I will try that. But I just realized that with the screenshots that I have sent you, the problem is with minx and maxx indeed. I specifically tried to keep a minimal dataset to have a working first prototype and here's what the data_dir looks like. Should I be getting bounding box errors? 

![image](https://user-images.githubusercontent.com/15706155/225080340-16dc60c0-2c61-4864-b0cb-47ef2ebf140c.png)

**Comment by TolgaAktas** [comment]
That's indeed a good workaround, I will try that. But I just realized that with the screenshots that I have sent you, the problem is with minx and maxx indeed. I specifically tried to keep a minimal dataset to have a working first prototype and here's what the data_dir looks like. Should I be getting bounding box errors?

![image](https://user-images.githubusercontent.com/15706155/225080540-810521fb-765a-4b34-9020-c8460e14129e.png)

**Comment by adamjstewart** [comment]
The bounding box errors are just a symptom of https://github.com/Toblerity/rtree/issues/204, the real issue is that the intersection dataset contains 0 images. 

The reason that it contains 0 images is because `clean_set` and `noisy_set` don't contain any images from the same day, and therefore have no overlap. If you disable the time component, it should work.

**Comment by TolgaAktas** [comment]
I tried changing to the regex you provided but I think that leaves out a lot of essential information for the Dataset object to find the dataset. I am getting a "No Landsat8 data was found in '~/datasets/landsat/wrs1630/clean' " error with the new regex. Any way to just leave out the date component?

**Comment by adamjstewart** [comment]
Oops, try this:
```python
Landsat8.filename_regex = ".*_(?P<band>[A-Z0-9_]+)\."
```
We use `re.match`, not `re.search`, so it always starts looking from the beginning of the filename.

**Comment by TolgaAktas** [comment]
The datasets, the intersection dataset, sampler and loader get instantiated with errors but now the following arise. The errror is not originated in torchgeo per se, but somehow dataloader gets the wrong input type to fetch. Any ideas? 

Here's the code 
![image](https://user-images.githubusercontent.com/15706155/225112828-3fea07e2-16dd-4442-b1f5-2365b54b2089.png)

The error message:

![image](https://user-images.githubusercontent.com/15706155/225113175-3c8d3782-6eea-4769-a9cf-2de46504f5a8.png)

**Comment by TolgaAktas** [comment]
Ok, this helps working around the issue. I can correctly build and sample and get batches. But the images from two sets are still the identical (see torch.allclose() at the bottom) although the datasets and their images are different. Here's the code and the data_dir tree showing that the images are different. Any ideas ? 

![image](https://user-images.githubusercontent.com/15706155/225129916-a2311165-8eff-45bb-b4af-f662e24e622f.png)


![image](https://user-images.githubusercontent.com/15706155/225129818-26f1cc2d-e8c5-4ccc-b11e-128dcc1f7dcd.png)


![image](https://user-images.githubusercontent.com/15706155/225129770-684d903c-ac27-4944-9640-f26239d1892e.png)

**Comment by adamjstewart** [comment]
It could be that it's sampling from a corner where both images have nodata pixels. I would try printing the sample and checking to see if it's all zeros. Also print the shape to make sure you're getting what you want. Also, the data loader returns dictionaries, not images. Shouldn't you be using `elem["image"]` to access the image?

**Comment by TolgaAktas** [comment]
This might also have to do with my custom collate_fn function, looking into it. I wiill close the ticket for now since I think we solved  the main problem !

**Comment by adamjstewart** [comment]
Great! Feel free to reopen or open new issues/discussions if you have any other problems!
