### ISSUE TITLE
ChesapeakeCVPR: NLCD cmap may be incorrect

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#1183]
### Description

The NLCD cmap in the ChesapeakeCVPR dataset only contains 17 labels, while the official NLCD documentation claims there should be 20 classes: https://www.mrlc.gov/data/legends/national-land-cover-database-class-legend-and-description. We should keep these in sync, even if certain classes don't appear in the dataset.

Our cmap adds 0, and removes 51, 72, 73, 74 classes.

### Steps to reproduce

N/A

### Version

0.5.0.dev0 (e8b9a9ebe3f8ed1ea1090b11f79a92485ebb945d)

**Comment by calebrob6** [comment]
51, 72, 73, 74 are all alaska only (see the link above) and the dataset is not in alaska
0 is nodata

**Comment by adamjstewart** [comment]
What about the name? Both MLHub and LILA call it Chesapeake Land Cover.

**Comment by calebrob6** [comment]
I think that's ambiguous with e.g. the new Chesapeake Land Cover dataset that was released
