### ISSUE TITLE
Multi-gpu training error

### ISSUE THREAD

**Issue by snreumich** [microsoft/torchgeo#1198]
### Description

Is multi-gpu training supported on Windows? I can train with 1 GPU but trying multiple devices leads to "RuntimeError: Distributed package doesn't have NCCL built in". Tried setting the environment variable `PL_TORCH_DISTRIBUTED_BACKEND=gloo` but that does not help either. 

### Steps to reproduce

1.  Set `devices: 1,2` in the `conf\landcoverai.yaml` file
2. Run `python train.py config_file=conf\landcoverai.yaml`

Output: 
```
Global seed set to 0
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [t2]:58152 (system error: 10049 - The requested address is not valid in its context.).
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [t2]:58152 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [t2]:58152 (system error: 10049 - The requested address is not valid in its context.).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [t2]:58152 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "d:\Dev\torchgeo-main\train.py", line 236, in <module>
    main(conf)
  File "d:\Dev\torchgeo-main\train.py", line 214, in main
    trainer.fit(model=task, datamodule=datamodule)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\strategies\launchers\multiprocessing.py", line 113, in launch
    mp.start_processes(
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\strategies\launchers\multiprocessing.py", line 139, in _wrapping_function
    results = function(*args, **kwargs)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1048, in _run
    self.strategy.setup_environment()
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\strategies\ddp_spawn.py", line 138, in setup_environment
    self.setup_distributed()
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\strategies\ddp_spawn.py", line 174, in setup_distributed
    _init_dist_connection(
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\fabric\utilities\distributed.py", line 245, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\torch\distributed\distributed_c10d.py", line 998, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
```

### Version

0.5.0.dev0 commit 88df515

**Comment by adamjstewart** [comment]
This looks like an issue with your PyTorch installation, not with TorchGeo.

It might be possible to get gloo to work. Can you try the following code, but replace nccl with gloo? I've never tried to do distributed training before, but this is what I could find: https://lightning.ai/docs/pytorch/stable/accelerators/gpu_intermediate.html#optimize-multi-machine-communication

Note that most operations are only supported on the GPU for gloo, so using gloo is unideal: https://pytorch.org/docs/stable/distributed.html#backends

It might be worth reaching out to the people who packaged PyTorch in conda-forge. I don't use Conda or Windows, so I'm unfortunately not very helpful. You can also try Spack or Linux if that's an option.

**Comment by adamjstewart** [comment]
Actually, I'm not even sure NCCL is supported on Windows. According to [CMakeLists.txt](https://github.com/pytorch/pytorch/blob/v2.0.0/CMakeLists.txt#L233,L235), it seems like NCCL is only available on Linux, not macOS or Windows. So your best bet is to figure out how to use gloo or MPI, or to use Linux.

**Comment by snreumich** [comment]
Thanks for those links Adam. I could get it to run with gloo by adding this to train.py:

```
from lightning.pytorch.strategies import DDPStrategy
# Explicitly specify the process group backend 
ddp = DDPStrategy(process_group_backend="gloo",find_unused_parameters=False)
```


However, this errors out after the training epochs are done (see run below for 3 epochs). Seems to be looking for a checkpoint that was never created:

Global seed set to 0
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Global seed set to 0
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [t2]:52826 (system error: 10049 - The requested address is not valid in its context.).
[rank: 1] Global seed set to 0
WARNING! The experiment directory, output\inria_test, already exists, we might overwrite data in it!
[rank: 1] Global seed set to 0
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [t2]:52826 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [t2]:52826 (system error: 10049 - The requested address is not valid in its context.).
[W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [t2]:52826 (system error: 10049 - The requested address is not valid in its context.).
----------------------------------------------------------------------------------------------------
distributed_backend=gloo
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\callbacks\model_checkpoint.py:613: UserWarning: Checkpoint directory D:\Dev\torchgeo-main\output\inria_test exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name          | Type             | Params
---------------------------------------------------
0 | model         | Unet             | 14.3 M
1 | loss          | CrossEntropyLoss | 0
2 | train_metrics | MetricCollection | 0
3 | val_metrics   | MetricCollection | 0
4 | test_metrics  | MetricCollection | 0
---------------------------------------------------
14.3 M    Trainable params
0         Non-trainable params
14.3 M    Total params
57.313    Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Sanity Checking DataLoader 0: 100%|██████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.05s/it]C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py:536: PossibleUserWarning: It is recommended to use `self.log('val_loss', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
  warning_cache.warn(
C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py:536: PossibleUserWarning: It is recommended to use `self.log('val_MulticlassAccuracy', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
  warning_cache.warn(
C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py:536: PossibleUserWarning: It is recommended to use `self.log('val_MulticlassJaccardIndex', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
  warning_cache.warn(
C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0: 100%|█████████████████████████████████████████████████| 81/81 [01:38<00:00,  1.22s/it, loss=0.423, v_num=6_47]C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py:536: PossibleUserWarning: It is recommended to use `self.log('train_MulticlassAccuracy', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
  warning_cache.warn(
C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\connectors\logger_connector\result.py:536: PossibleUserWarning: It is recommended to use `self.log('train_MulticlassJaccardIndex', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
  warning_cache.warn(
Epoch 2: 100%|█████████████████████████████████████████████████| 81/81 [01:35<00:00,  1.18s/it, loss=0.356, v_num=6_47]`Trainer.fit` stopped: `max_epochs=3` reached.
Epoch 2: 100%|█████████████████████████████████████████████████| 81/81 [01:38<00:00,  1.21s/it, loss=0.356, v_num=6_47]
[rank: 1] Global seed set to 0
[rank: 0] Global seed set to 0
Restoring states from the checkpoint path at D:\Dev\torchgeo-main\output\inria_test\checkpoint-epochepoch=02-val_lossval_loss=0.39.ckpt
Traceback (most recent call last):
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 842, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1056, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 998, in _restore_modules_and_callbacks
    self._checkpoint_connector.resume_start(checkpoint_path)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\trainer\connectors\checkpoint_connector.py", line 90, in resume_start
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 359, in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
  File "C:\Users\admin\Miniconda3\envs\torchgeo\lib\site-packages\lightning\fabric\plugins\io\torch_io.py", line 84, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint at {path} not found. Aborting training.")
FileNotFoundError: Checkpoint at D:\Dev\torchgeo-main\output\inria_test\checkpoint-epochepoch=01-val_lossval_loss=0.29.ckpt not found. Aborting training.

**Comment by adamjstewart** [comment]
Are you able to reproduce this bug without TorchGeo? Maybe something like https://lightning.ai/docs/pytorch/stable/notebooks/lightning_examples/mnist-hello-world.html. You may need to add checkpointing to get the same error. So far this new error message seems like a Lightning bug, not a TorchGeo bug.

**Comment by adamjstewart** [comment]
Did you ever get this working?

**Comment by adamjstewart** [comment]
No response from @snreumich, closing. Feel free to reopen if you're still having this issue.
