### ISSUE TITLE
ImageTarget Dataset

### ISSUE THREAD

**Issue by ashnair1** [microsoft/torchgeo#120]
Hello, I recently came across `torchgeo` and would like to help out in extending it for object detection and instance segmentation tasks. 

Is there a recommended way to add datasets that contain both images and targets? According to the wiki it seems this was being discussed.

**Comment by isaaccorley** [comment]
I'll defer to others to clarify this more, but you can simply inherit from torchgeo.datasets.VisionDataset and then make sure your output is a dict with tensors for "image", "mask", and "boxes". The torchgeo.datasets.LandCoverAI dataset is a good reference implementation.

**Comment by ashnair1** [comment]
Thanks for the clarification. One follow up question I had is regarding the choice of parent class. Spacenet for example has images as geotiffs (tiled to a specific size) and labels as a geojson. Since it has geospatial info, it would inherit from `GeoDataset` correct?

**Comment by isaaccorley** [comment]
I believe you would need to inherit from the VectorDataset class which has support for geojson annotations. I believe the only dataset we have similar to what you are suggesting would be the torchgeo.datasets.cbf.CanadianBuildingFootprints dataset in which case I would follow that implementation.

**Comment by ashnair1** [comment]
I suppose since it contains both rasters (GTiffs) and vectors (geojsons) it could inherit from both `RasterDataset` and `VectorDataset`

**Comment by adamjstewart** [comment]
Hi @ashnair1, welcome to TorchGeo! In TorchGeo, we have two kinds of datasets:

1. `VisionDataset`: for datasets that lack geospatial metadata
2. `GeoDataset`: for datasets that have geospatial metadata

Since your dataset includes GeoTIFFs and GeoJSONs, it sounds like it falls into the latter. In a `GeoDataset`, we build up an `index` containing the bounding boxes of each image tile so that we can query it later. `RasterDataset` and `VectorDataset` are just two common abstractions for directories full or raster or vector files, you don't necessarily have to use them.

I think the best strategy depends on the dataset file structure. Is the dataset distributed with many image tiles and vector labels for each tile, or many image tiles and a single giant vector label file? The main goal is that the index covers all possible locations that can be sampled from, the the `__getitem__` should return both image and mask.

**Comment by ashnair1** [comment]
Hi @adamjstewart, thanks a lot for the explanation. The Spacenet directory (downloaded using the radiant earth mlhub api - [here](https://registry.mlhub.earth/spacenet_1/)) structure looks like this:

```
├── sn1_AOI_1_RIO_img1
│   ├── 8Band.tif
│   ├── RGB.tif
│   └── stac.json
├── sn1_AOI_1_RIO_img1-labels
│   ├── labels.geojson
│   └── stac.json
├── sn1_AOI_1_RIO_img2-labels
│   ├── labels.geojson
│   └── stac.json
└── sn1_AOI_1_RIO_img2-labels
    ├── labels.geojson
    └── stac.json
....
....
```

The image directories and labels directories are grouped together.

**Comment by adamjstewart** [comment]
Perfect, that's the easier case then. If each image image has a corresponding mask file, you can just add one or the other to the index (this will allow you to subclass from RasterDataset or VectorDataset). Then the only thing you need to change is the `__getitem__`. In addition to loading the image file, you'll also load the mask file and return both.

**Comment by ashnair1** [comment]
So to recap, I can subclass from either RasterDataset or VectorDataset depending on whether I add the images or the geojson to the index respectively. 

If I were to subclass from the VectorDataset, the geojson gets rasterised and added to the index. Once that's done, `__getitem__` needs to return the images and rasterised geojson. In this particular case the result will be a tuple of 3 items - the 8 band tif (tensor of shape (8, H, W)), the RGB tif (tensor of shape (3, H, W)) and the geojson mask (1, H, W).

**Comment by adamjstewart** [comment]
If the 8-band tif already contains the same information as the RGB tif, I wouldn't bother loading/returning it at all. Instead of tuples we use dictionaries so that it's easier to keep track of what each component is.

**Comment by ashnair1** [comment]
Sure. But I believe the RGB tif is the pan sharpened version hence the three elements. 

I'll confirm this and modify accordingly.

**Comment by adamjstewart** [comment]
If they're all the same resolution I would just stack them into a single Tensor.

**Comment by ashnair1** [comment]
They're not. They're also of different sizes. The 8 band tif has shape `(8, 101, 110)` while the RGB tif has shape `(3, 406, 438)`

**Comment by adamjstewart** [comment]
The SpaceNet dataset has been merged, so I think that answers most of the questions in this issue. There's still a lot we could do to refactor things and have a base class that does most of the work here, but let's wait until we get a few more example datasets like this before refactoring. Thanks for the discussion and PRs!
