### ISSUE TITLE
Python 3.7 is due to reach its scheduled upstream end-of-life on June 27th, 2023

### ISSUE THREAD

**Issue by arkanoid87** [microsoft/torchgeo#1309]
### Summary

torch 2.0.0 (Mar 15 2023) package requires: Python >=3.8.0
torchgeo 0.4.1 (Apr 12 2023) package requires: Python ~=3.7

**Comment by adamjstewart** [comment]
TorchGeo has already dropped support for Python 3.7 and 3.8 in [main](https://github.com/microsoft/torchgeo/blob/b66fea6fa13edc181c961a9efb6e72a5d2f431c7/setup.cfg#L59). This will be included in the 0.5.0 release (sometime this summer).

**Comment by adamjstewart** [comment]
TorchGeo is perfectly compatible with torch stable, 0.4.1 [supports](https://github.com/microsoft/torchgeo/blob/v0.4.1/setup.cfg#L57) and is tested against PyTorch 2.0.0.

If you need Python 3.7 support, pip should automatically select the newest version of PyTorch and TorchGeo that still supports Python 3.7. If you don't need Python 3.7 support, the latest version of everything should work fine.

**Comment by isaaccorley** [comment]
@arkanoid87 Can you explain your venv setup? Python~=3.7 is not the same as Python==3.7 so you should still be able to use python 3.8+ and torchgeo to work with torch 2.0.
