### ISSUE TITLE
Download NAIP Imagery

### ISSUE THREAD

**Issue by patriksabol** [microsoft/torchgeo#1419]
### Issue

How to download NAIP imagery for Chesapeak13? Labels for Chesapeake13 are downloaded automatically, but there is no information, how to download correspond NAIP imagery. In [tutorial](https://torchgeo.readthedocs.io/en/latest/tutorials/getting_started.html), there is link to blob to download 4 particular raster, but what about the rest?

### Fix

I suggest to add this information to documentation.

**Comment by isaaccorley** [comment]
Setting `dataset = Chesapeake13(root="data", download=True)` downloads the labels and imagery. Are you sure it didn't download the imagery? I just tested and it works fine for me.

The root directory should contain the following files after downloading:

<img width="294" alt="image" src="https://github.com/microsoft/torchgeo/assets/22203655/22cb2585-3f8e-4ae5-9c8b-2c3a757fee5a">

**Comment by patriksabol** [comment]
I think it is only mask of 13 classes. It does not contain any imagery. Chesapeake 13 inherits from Chesapeake, where [here](https://github.com/microsoft/torchgeo/blob/ae3a4cb3a201cb20ef8a7524422909c95b4592be/torchgeo/datasets/chesapeake.py#L42) it says, it is no imagery dataset. 
Moreover, gdalinfo Baywide_13Class_20132014.tif
`Band 1 Block=128x128 Type=Byte, ColorInterp=Palette
  Min=1.000 Max=12.000 
  Minimum=1.000, Maximum=12.000, Mean=3.588, StdDev=1.478
  NoData Value=0
  Overviews: 249563x439170, 124782x219585, 62391x109793, 31196x54897, 15598x27449, 7799x13725, 3900x6863, 1950x3432, 975x1716, 488x858, 244x429
  Metadata:
    RepresentationType=THEMATIC
    STATISTICS_COVARIANCES=2.184897016039103
    STATISTICS_MAXIMUM=12
    STATISTICS_MEAN=3.587997581131
    STATISTICS_MINIMUM=1
    STATISTICS_SKIPFACTORX=1
    STATISTICS_SKIPFACTORY=1
    STATISTICS_STDDEV=1.4781397146546
  Image Structure Metadata:
    NBITS=4
  Color Table (RGB with 16 entries)
    0: 0,0,0,0
    1: 0,197,255,255
    2: 0,168,132,255
    3: 38,115,0,255
    4: 76,230,0,255
    5: 163,255,115,255
    6: 255,170,0,255
    7: 255,0,0,255
    8: 156,156,156,255
    9: 0,0,0,255
   10: 115,115,0,255
   11: 230,230,0,255
   12: 255,255,115,255
   13: 197,0,255,255
   14: 0,0,0,255
   15: 0,0,0,255
` 

Which tiles should I download to match these 13-class labels? What is the purpose of NAIPChesapeakeDataModule, if it downloads Chesapeake13 labels, but no NAIP Imagery?

**Comment by isaaccorley** [comment]
Ah I see what you mean. The purpose of the dataset is to be combined with NAIP or any other image dataset that has overlapping areas. Maybe @adamjstewart or @calebrob6 can answer where the imagery can be downloaded other than from any of the numerous online NAIP sources.

**Comment by patriksabol** [comment]
Thank you for clarification! My intention is to get exact imagery, on which the labeling (Chesapeake13) was done. Could be those from ChesapeakeCVPR zip?

**Comment by adamjstewart** [comment]
@calebrob6 any thoughts on this one?

**Comment by adamjstewart** [comment]
Note that `Chesapeake13` no longer exists after #2214, but the question still applies for the remaining Chesapeake state-specific products.

**Comment by calebrob6** [comment]
The Chesapeake state-specific products are _just_ land cover masks -- you would have to download them, get their areas and times of interest then use some service like the Planetary Computer to get matching NAIP data (example https://planetarycomputer.microsoft.com/dataset/naip#Example-Notebook).

We definitely could have a tutorial for doing this, but I think it should be a different issue.
