### ISSUE TITLE
USAVars Augmentation maps to 0

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#1432]
### Description

In the USAVars Datamodule, the default augmentation from NonGeoDatamodule is used. However, the dataset returns uint8 data, and it comes out of the augmentation still as uint8. This means you get an error when trying to train but also that your input images are just all zeros.

### Steps to reproduce
```
dm = USAVarsDataModule(root="path/to/usa_vars", batch_size=16)
dm.setup("fit")
dl = dm.train_dataloader()
batch = next(iter(dl))
aug_batch = dm.aug(batch)
print(aug_batch["image"].max())
```

### Version

'0.5.0.dev0'

**Comment by nilsleh** [comment]
Also not sure to what extent other current datasets might have the same issue because it's a silent bug.

**Comment by adamjstewart** [comment]
This is another reason I want #985. Although I don't think rasterio can statically infer the type of the file, so maybe that wouldn't help.

**Comment by adamjstewart** [comment]
We could certainly warn, but I want to make sure warnings are uncommon. I also really want to get rid of our `AugmentationSequential` wrapper and instead use the Kornia one. The biggest thing holding us back is https://github.com/kornia/kornia/issues/2119. I started working on this but quickly found it more difficult than I expected.

I think one of the following solutions would be fine:

* Implement https://github.com/kornia/kornia/issues/2119 and drop our `AugmentationSequential`
* Drop our `AugmentationSequential` and use `data_keys` everywhere
* Remove type conversion from our `AugmentationSequential` and force datasets/datamodules/trainers to handle it
* Add a warning when we convert dtypes

There are roughly sorted in order from "this is what I want long-term" to "this would be tolerable short-term".
