### ISSUE TITLE
Setting up Dev Env.

### ISSUE THREAD

**Issue by bundle-adjuster** [microsoft/torchgeo#1485]
### Description

I am not sure if this is an issue only with me or is it happening with others as well. I have however tried with 2 different environments(macos 13.3.1 (a) and Ubuntu 20.04) and still the issue persists.

When I run 

"$conda env create -f environment.yml"

It sort of gets stuck at solving environment forever. Not sure if this is an issue with conda or my system. Attaching screenshot of my tmux which has been running for over 24 hours.

<img width="1787" alt="Screenshot 2023-07-19 at 1 08 04 PM" src="https://github.com/microsoft/torchgeo/assets/53701742/66e653c8-8ef9-4733-a663-44f0673ca6e9">

### Steps to reproduce

```shell

conda env create -f environment.yml

```

### Version

8b53304
```[tasklist]
### Tasks
```

**Comment by adamjstewart** [comment]
I have very little experience with conda but usually long concretization times imply that something isn't satisfiable and it is trying to come up with a useful error message. The other TorchGeo devs have more experience with conda and might be able to advise. If you want to try Spack I can help on that side.

**Comment by calebrob6** [comment]
Hey @bundle-adjuster, if your goal is to get an environment with torch + CUDA, torchgeo, etc. you can use something like this:

```
name: torchgeo
channels:
  - conda-forge
dependencies:
  - gdal
  - python<3.11
  - pip
  - pip:
    - black[jupyter]>=21.8
    - flake8>=3.8
    - torchgeo[datasets,docs,style,tests]>=0.4.0
    - isort[colors]>=5.8
    - jupyter
    - mercantile>=1.2
    - mypy>=0.900
    - pytest>=6.1.2
    - pytest-cov>=2.4
    - requests
    - requests-auth>=0.6
    - types-requests
    - utm
```

**Comment by bundle-adjuster** [comment]
@calebrob6 will check it out and revert! Thanks!
