### ISSUE TITLE
Issue with sampling tiles near boundaries of a dataset

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#149]
For benchmarking, we're using a ZipDataset containing Landsat and CDL imagery. See the below image for the relative coverage of both datasets. When sampling, the recommended strategy is to pass the index of the tile-based dataset (Landsat) since it has less coverage than the CDL dataset. However, some of the Landsat tiles are on the border of the CDL dataset. When sampling, if the sampler chooses a patch that is within a Landsat tile but outside of the CDL tile, it raises an IndexError. Specifying `roi=cdl.index.bounds` doesn't help because the Landsat tile in question is partially within the bounds of the CDL dataset. At first glance, I don't see any easy way to resolve this issue.

![image](https://user-images.githubusercontent.com/12021217/133935157-e4c67765-9c79-40c4-880c-5d5d5e0b288f.png)

**Comment by calebrob6** [comment]
This is conceptually related to the ZipDataset redesign issue. Here, we actually want something like an IntersectionDataset as we want to sample from areas that are guaranteed to have data in all layers. In the IntersectionDataset constructor you would do something like create a new index where the shapes are clipped to the intersection of the component datasets' bounds.
