### ISSUE TITLE
radiant earth download collection option

### ISSUE THREAD

**Issue by ashnair1** [microsoft/torchgeo#151]
Datasets from radiant earth are made of collections. For most datasets, there are at most 2 collections i.e. images and labels. 

However, for the spacenet datasets each collection is composed of both images and labels and it is possible to have more than 2 collections. This is because the collections are made according to AOIs. 

For example, [Spacenet 2](https://registry.mlhub.earth/spacenet_2/) has four collections:
- sn2_AOI_2_Vegas
- sn2_AOI_3_Paris
- sn2_AOI_4_Shanghai
- sn2_AOI_5_Khartoum

The current [download_radiant_mlhub](https://github.com/microsoft/torchgeo/blob/58d05d595077f9f751c0e37e87d8c212643e8622/torchgeo/datasets/utils.py#L128) works at the dataset level. When used for large datasets it's possible it can be interrupted. So having a function that works at the Collection level would be useful. Opened a PR for this.

**Comment by adamjstewart** [comment]
> The current download_radiant_mlhub works at the dataset level. When used for large datasets it's possible it can be interrupted. So having a function that works at the Collection level would be useful.

Is the intent of this to allow for datasets that download only a subset of collections, or for datasets that download incrementally, one collection at a time?

**Comment by ashnair1** [comment]
The former. By default downloading a dataset will download all collections one by one. 

This function can enable finer control over which collections are downloaded. 

Note: I think SpaceNet is the only dataset organised like this.
