### ISSUE TITLE
Trouble initializing Landsat8 dataset with Level 2 data

### ISSUE THREAD

**Issue by TolgaAktas** [microsoft/torchgeo#1518]
### Description

I am experimenting with L2 surface reflectance data of Landsat8, and I have a directory of product subdirectories named after the product ID. The names of the L2 products are slightly different from those of L1 such as: 

L1: LC08_L1GT_016030_20180613_20200831_02_T2_B9.TIF
L2: LC08_L2SP_016030_20160911_20200906_02_T1_SR_B9.TIF

Although the dataset object gets created and gives me a valid length of the files, I am not able to use the train_loader to obtain batches.

### Steps to reproduce

```
import os
import torch
import torchgeo
import collections

import matplotlib.pyplot as plt

from torch.utils.data import DataLoader
from torchgeo.datasets import Landsat8, stack_samples,BoundingBox
from torchgeo.samplers import RandomGeoSampler,RandomBatchGeoSampler

from typing import * 


data_path = "<directory>/landsat/level2_1630"
bands = ["B1","B2","B3","B4","B5","B6","B7","B8","B9","B10", "B11","QA_PIXEL"]
sr_bands = ["SR_"+band for band in bands]
rgb_bands = ['SR_B4', 'SR_B3', 'SR_B2']


Landsat8.all_bands = sr_bands
Landsat8.rgb_bands = rgb_bands
Landsat8.filename_regex = ".*_(?P<band>[A-Z0-9_]+)\."

def _list_dict_to_dict_list(samples: Iterable[Dict[Any, Any]]) -> Dict[Any, List[Any]]:
    """Convert a list of dictionaries to a dictionary of lists.

    Args:
        samples: a list of dictionaries

    Returns:
        a dictionary of lists

    .. versionadded:: 0.2
    """
    collated = collections.defaultdict(list)
    for sample in samples:
        for key, value in sample.items():
            collated[key].ap

def pick_images(samples: Iterable[Dict[Any, Any]]) -> torch.Tensor:
    
    collated: Dict[Any, Any] = _list_dict_to_dict_list(samples)
    
    if "image" in collated.keys():
        batch = torch.stack(collated["image"])
        return batch





l2_data = Landsat8(root = data_path, bands = sr_bands)
print(l2_data)

sampler = RandomBatchGeoSampler(l2_data,size=(320,320),batch_size=10,length=120)
loader = DataLoader(l2_data, 
                    batch_sampler = sampler, 
                    collate_fn=pick_images,
                    num_workers=4,
                    pin_memory=False,
                    drop_last=False)

for elem in loader:
    a = elem
    break

```
![image](https://github.com/microsoft/torchgeo/assets/15706155/5ca8d5de-abb4-4318-9358-d2bb74a28ebc)

### Version

0.5.0.dev0

**Comment by adamjstewart** [comment]
A few possible bugs:

1. You shouldn't need to change `all_bands`, `rgb_bands`, or `filename_regex` for `Landsat8`, did you encounter an issue with the default values?
2. Your `_list_dict_to_dict_list` contains a bug, it doesn't return anything. You should be able to use `torchgeo.datasets.stack_samples` instead of `pick_images` if you want to write less code and remain bug-free.

**Comment by TolgaAktas** [comment]
I was able to get batches and display images with Level 2 data now, but it fails to construct a IntersectionDataset when I try to do the following: 

'''
shadow_path = "/dirs/data/euphrates/datasets/landsat/sorted_level2/shadow_image"
clean_path  = "/dirs/data/euphrates/datasets/landsat/sorted_level2/clean/"

shadow_set  = Landsat8(root = shadow_path, bands = bands)
clean_set   = Landsat8(root = clean_path, bands = bands)
dataset = IntersectionDataset(shadow_set, clean_set)

'''
It's giving me a "Datasets have no spatiotemporal intersection" error.

This is similar to the problem that I was running into earlier, when I was working with Level1 data to construct IntersectionDataset, which we solved by rewriting the regex to 

When I do the similar trick for this, the resulting dataset's length is len(dataset1) * len(dataset2), which shouldn't happen.

**Comment by adamjstewart** [comment]
If the images don't occur at the same time, then they won't have any overlap. I'm guessing the only reason we rewrote the regex is to pretend the images don't have a datetime string. 

The number of overlapping combinations could be much larger than the original number of images if images overlap near their borders. You'll have to print the filenames to confirm but I'm guessing they'll all overlap on a corner or edge or something.

**Comment by adamjstewart** [comment]
Ah, that makes perfect sense then. If every image in the dataset overlaps with every other image in the dataset, then you should definitely expect `len(ds) == len(ds1) * len(ds2)`.

**Comment by TolgaAktas** [comment]
I get the following problem however:

Commenting out  ''' Landsat8.filename_regex = ".*_(?P<band>[A-Z0-9_]+)\." ''', I get error in just loading a batch from the Intersection dataset : "Datasets have no spatiotemporal intersection"

But if I add the filename_regex override, I get the following error with this code:

Any recommendation as to how I can make both happy, like I was doing with L1 data? 

Between L1 and L2, the naming is slightly different, do you think that matters? 

'''
import os
import torch
import torchgeo
import collections

import matplotlib.pyplot as plt

from torch.utils.data import DataLoader
from torchgeo.datasets import Landsat8, stack_samples,BoundingBox,IntersectionDataset
from torchgeo.samplers import RandomGeoSampler,RandomBatchGeoSampler

from typing import * 

PROJ_DIR = "/dirs/data/euphrates"

data_path = "/dirs/data/euphrates/datasets/landsat/level2_1630"
# bands = ["B1","B2","B3","B4","B5","B6","B7","B8","B9","B10", "B11","QA_PIXEL"]
# bands = ["SR_B1","SR_B2","SR_B3","SR_B4","SR_B5","SR_B6","SR_B7","QA_PIXEL"]

bands = ["SR_B2","SR_B3","SR_B4","QA_PIXEL"]
rgb_bands = ['SR_B4', 'SR_B3', 'SR_B2']
num_bands = len(bands) - 1

Landsat8.all_bands = bands
Landsat8.rgb_bands = rgb_bands
Landsat8.filename_regex = ".*_(?P<band>[A-Z0-9_]+)\."

l2_data = Landsat8(root = data_path, bands = bands)
# l2_data = Landsat8(root = data_path)
print(l2_data)

sampler = RandomBatchGeoSampler(l2_data,size=(320,320),batch_size=10,length=120)
loader = DataLoader(l2_data, 
                    batch_sampler = sampler, 
                    collate_fn=stack_samples,
                    num_workers=4,
                    pin_memory=False,
                    drop_last=False)

for elem in loader:
    a = elem
    break
''' 
which gets me this:

![image](https://github.com/microsoft/torchgeo/assets/15706155/f146901b-8b9c-4c2e-9838-21cbce4d84b3)

**Comment by adamjstewart** [comment]
Wait a minute. If all of your images are of the same location but you ignore the time component, won't the sampler return a bounding box for all time, and won't the `__getitem__` merge all files such that you'll only ever see the top file? I'm not sure exactly what behavior you're expecting but I don't think it will work.

**Comment by adamjstewart** [comment]
@TolgaAktas are you still experiencing any issues?

**Comment by adamjstewart** [comment]
No response, closing this issue. Feel free to reopen if you're still having issues and I'll be happy to help!
