### ISSUE TITLE
Update Rwanda Field Boundary dataset

### ISSUE THREAD

**Issue by calebrob6** [microsoft/torchgeo#1600]
The RwandaFieldBoundary dataset plots a mask even though this is unnecessary -- change the plot function to ignore the mask key in a sample if it doesn't exist.

Also, the current logic verifies the integrity of the dataset by checking to see if the number of files is `(num_patches * 6) + 1`. This is fragile because, as a user, I would not expect a dataloader class to fail if I added accessory files to the directory where the dataset is stored.

**Comment by burakekim** [comment]
Wanted to jump on this, but could not obtain a RadiantHub key. They operate under [a different name and website](https://mlhub.earth/), which does not seem to provide keys.

**Comment by adamjstewart** [comment]
@burakekim if you want to take a stab at this, the dataset has been ported to Source Cooperative now and should be relatively easy to automatically download. The second request has already been solved, only remaining thing is skipping fake mask plotting.
