### ISSUE TITLE
Support for pathlib

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#1616]
### Summary

We should add support for Python's [pathlib](https://docs.python.org/3/library/pathlib.html) module.

### Rationale

Users may want to pass in a `Path` object instead of a string.

### Implementation

The type hints will change from `str` to `Union[str, bytes, os.PathLike]` according to [PEP 519](https://peps.python.org/pep-0519/#provide-specific-type-hinting-support).

**Comment by pioneerHitesh** [comment]
I would like to contribute to this, can this be assigned to me?

**Comment by adamjstewart** [comment]
Assigned, thanks for the help @pioneerHitesh!

**Comment by adamjstewart** [comment]
sklearn actually did the exact same thing in their latest release: https://github.com/scikit-learn/scikit-learn/pull/27468

**Comment by pioneerHitesh** [comment]
@adamjstewart sir is there any work left on this?

**Comment by kvenkman** [comment]
If this is still an issue, could I contribute to this?

**Comment by adamjstewart** [comment]
@pioneerHitesh was working on this, up to him whether or not he wants to let you take over.

P.S. torchvision 0.17 was released a couple days ago. Does this add support for pathlib to their download/extract functions? This will make the conversion much easier in TorchGeo, I think that's the only thing we were waiting on.

**Comment by pioneerHitesh** [comment]
@adamjstewart  The [PR](https://github.com/pytorch/vision/pull/8200) has not been made into stable release yet. Regarding taking over of the project. I am more inclined to complete the work myself although i appreciate @kvenkman interest in it.

**Comment by kvenkman** [comment]
Sounds good, happy to help as needed @pioneerHitesh!

**Comment by pioneerHitesh** [comment]
@adamjstewart should we start work?
