### ISSUE TITLE
Calling EuroSATDataModule plot generates the plot twice

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1627]
### Description

Possibly a Jupyter specific issue, but calling the `dataset.plot()` function generates two plots:

<img width="397" alt="image" src="https://github.com/microsoft/torchgeo/assets/11855322/969fb7a3-6317-4210-a14b-8e0201b3366d">

### Steps to reproduce

```
from torchgeo.datamodules import EuroSATDataModule

datamodule = EuroSATDataModule(batch_size=batch_size, root="data", num_workers=num_workers)
datamodule.prepare_data()
datamodule.setup('fit')

sample = datamodule.train_dataset[2]
datamodule.train_dataset.plot(sample) # plots twice
```

### Version

0.5.0

**Comment by adamjstewart** [comment]
Can you see if replacing:
```python
datamodule.train_dataset.plot(sample)
```
with:
```python
fig = datamodule.train_dataset.plot(sample)
```
solves the issue? The plot method returns the figure, and Jupyter likes to print/plot/display anything returned on the last line of a cell just like iPython does.

**Comment by robmarkcole** [comment]
Yes that fixes it

<img width="398" alt="image" src="https://github.com/microsoft/torchgeo/assets/11855322/93852164-3d68-49d4-a085-e544c56b8b07">

**Comment by adamjstewart** [comment]
Great! I think we can call this a quirk of Jupyter and not a bug in TorchGeo.
