### ISSUE TITLE
Inconsistency in Sentinel 2 band names in transforms tutorial and eurosat dataset

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1635]
### Issue

In the [tutorial](https://torchgeo.readthedocs.io/en/stable/tutorials/transforms.html) they are `B1`, `B2` etc but in [the dataset](https://github.com/microsoft/torchgeo/blob/main/torchgeo/datasets/eurosat.py) `B01`, `B02` etc. To avoid confusion it would be good to stick to one format. I've noticed this whilst adapting the tutorial

### Fix

Sitck to `B01`, `B02` etc

**Comment by adamjstewart** [comment]
Not sure how to decide between the two. https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR_HARMONIZED uses B1 instead of B01. I also don't like B08A, that should definitely be B8A regardless. Is there an official band name? What do the filenames look like?

**Comment by burakekim** [comment]
Inside the `.\S2A_MSIL2A_20200623T103031_N0214_R108_T32TMT_20200623T142851\GRANULE\L2A_T32TMT_A026131_20200623T103426\IMG_DATA\R60m` folder downloaded with `from sentinelhub.aws import AwsProductRequest`:

`['T32TMT_20200623T103031_AOT_60m.jp2', 'T32TMT_20200623T103031_B01_60m.jp2', 'T32TMT_20200623T103031_B02_60m.jp2', 'T32TMT_20200623T103031_B03_60m.jp2', 'T32TMT_20200623T103031_B04_60m.jp2', 'T32TMT_20200623T103031_B05_60m.jp2', 'T32TMT_20200623T103031_B06_60m.jp2', 'T32TMT_20200623T103031_B07_60m.jp2', 'T32TMT_20200623T103031_B09_60m.jp2', 'T32TMT_20200623T103031_B11_60m.jp2', 'T32TMT_20200623T103031_B12_60m.jp2', 'T32TMT_20200623T103031_B8A_60m.jp2', 'T32TMT_20200623T103031_SCL_60m.jp2', 'T32TMT_20200623T103031_TCI_60m.jp2', 'T32TMT_20200623T103031_WVP_60m.jp2']`

**Comment by robmarkcole** [comment]
In my own experience of querying stac catalogues, B01, B02 etc is the convention

**Comment by adamjstewart** [comment]
Alright, let's rename them to B01... in the tutorial and B8A in eurosat.py. Anyone want to open a PR?

**Comment by burakekim** [comment]
I can do that
