### ISSUE TITLE
Unable to log_model="all" with wandb_logger

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1641]
### Description

Configured to log all checkpoints, but only a single is logged

### Steps to reproduce

```python
from lightning.pytorch.loggers import WandbLogger

wandb_logger = WandbLogger(
    project="eurosat-test3", 
    name="imagenet", 
    log_model="all", 
    save_dir = "wandb_logs_tests"
)

trainer = Trainer(
    logger=wandb_logger,
    min_epochs=15,
    max_epochs=25,
)

trainer.fit(model=model, datamodule=datamodule)

glob("wandb_logs_tests/eurosat-test3/*/checkpoints/*.ckpt") # returns only a single checkpoint
```

### Version

0.5.0

**Comment by calebrob6** [comment]
Is this a torchgeo bug or lightning bug?

**Comment by robmarkcole** [comment]
I commented out `configure_callbacks(self)` and now all logs are created:

<img width="280" alt="image" src="https://github.com/microsoft/torchgeo/assets/11855322/e89b938f-7906-473f-8098-3fd264c6a75c">
