### ISSUE TITLE
trainers docs show configuring callbacks but these will not be used

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1642]
### Issue

The [trainer](https://torchgeo.readthedocs.io/en/stable/tutorials/trainers.html) docs show setting `callbacks=[checkpoint_callback, early_stopping_callback],` but if you run this you will get a warning:

```
The following callbacks returned in `LightningModule.configure_callbacks` will override existing 
callbacks passed to Trainer: EarlyStopping, ModelCheckpoint
```

Honestly I am not a fan of this behaviour, but regardless the docs need ammending

### Fix

The docs should state the behaviour of tasks, and show how to use a conventional lightning module in their place when the default behaviour is not desired

**Comment by calebrob6** [comment]
I think configure_callbacks should be removed from BaseTask

**Comment by adamjstewart** [comment]
Interesting, this is frustrating. I wish there was a way to set defaults without them overriding everything. We could leave it up to the user but it's annoying that everyone will have to add these every time they want them.
