### ISSUE TITLE
PyVista tests are not headless when run locally

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#1651]
### Description

If you run the idtrees tests locally, it will open a plot, and the tests will pause until you close this plot.

### Steps to reproduce

Ensure that PyVista is installed. Then run:
```console
> pytest tests/datasets/test_idtrees.py
```

### Version

0.6.0.dev0 (7a793f3437222136a0b4eba2fb1bc0fcd947f604)

**Comment by banesullivan** [comment]
In your `conftest.py`, add:

```py
import pyvista as pv

pv.OFF_SCREEN = True
```

**Comment by banesullivan** [comment]
I recommend you use https://github.com/pyvista/pytest-pyvista if performing plotting in your tests to handle regression testing and ensuring the generated plots are what you expect

**Comment by adamjstewart** [comment]
Thanks @banesullivan, that worked like a charm! We only have a single dataset that plots with pyvista so for now we can handle it in that specific test function.

**Comment by adamjstewart** [comment]
@banesullivan do we still need to use https://github.com/pyvista/setup-headless-display-action in CI or does `OFF_SCREEN` make this unnecessary?

**Comment by banesullivan** [comment]
You'll always need to set OFF_SCREEN in PyVista when running on CI. That action is deprecated from my perspective (though still maintained by the community I believe). You'll need to set up/install VTK with graphics libraries. I recommend using the newer vtk-osmesa wheels from Kitware moving forward as they bundle the necessary graphics dependencies. See https://discourse.vtk.org/t/status-update-vtk-python-wheels/11212

Let me know if you have any more questions on this. I'll try to see if we have a robust guide to testing with PyVista somewhere (because we should)

**Comment by adamjstewart** [comment]
I'd rather continue to simply `pip install pyvista` without digging into dependencies of dependencies. We only use pyvista for 1 test out of thousands. If we dropped support for plotting lidar point clouds, we wouldn't need a dependency on pyvista at all.

**Comment by banesullivan** [comment]
That's totally understandable! This custom pip-index for VTK and different distribution name have been a burden on the community for sure. Exciting news though:

> Changed in version 9.4: As of VTK 9.4, OSMesa and EGL support are included by default in the vtk wheels and can be selected at runtime. The vtk-osmesa wheels are no longer provided, and it is no longer necessary to install vtk-osmesa.

This means that moving forward after the 9.4 release, just `pip install pyvista`, set `pv.OFF_SCREEN = True` (can be set as an environment variable), and ensure `libosmesa` is installed (via system package manager) and this should all work smoothly.

-----

> We only use pyvista for 1 test out of thousands.

Honestly, I'd just put a conditional `pytest.mark.skipif` on it and call it a day.

Something like

```py
try:
    # importing the `pyvista.plotting` namespace will error if graphics dependencies aren't installed
    from pyvista.plotting import Plotter
except:
    Plotter = None

@pytest.mark.skipif(Plotter is None, reason="PyVista isn't installed properly")
def test_pyvista(...):
    ...
```
