### ISSUE TITLE
OSCD RuntimeError: Input type (torch.cuda.LongTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1652]
### Description

Using the OSCD datamodule with a segmentation task results in the error:
```
RuntimeError: Input type (torch.cuda.LongTensor) and weight type (torch.cuda.FloatTensor) should be the same
```
It is necessary to cast the image to a float to resolve this (using `x = batch["image"].float()`), which I verified using a custom task. However I'm pretty sure this is not the intention to do this

### Steps to reproduce

```python
from lightning.pytorch import Trainer
from torchgeo.datamodules import OSCDDataModule

datamodule = OSCDDataModule(
    num_workers=num_workers,
    download=True,
    bands="rgb"
)

task = SemanticSegmentationTask(
    model="unet",
    backbone="resnet18",
    weights=True,
    in_channels=6,
    num_classes=2,
    loss="ce",
    ignore_index=None,
)

trainer = Trainer(
    min_epochs=5,
    max_epochs=25,
)

_ = trainer.fit(model=task, datamodule=datamodule)
```

I note that the data is type int64:
```
datamodule.train_dataset[0]["image"].dtype
torch.int64
```

### Version

0.5.0

**Comment by adamjstewart** [comment]
This relates to #985. We currently don't have a good way to test this. OSCD isn't really intended for use with SemanticSegmentationTask, we need a new trainer for change detection. I would be fine with a PR that simply casts the image to float32.
