### ISSUE TITLE
HTTP internal server error when trying to download ``AbovegroundLiveWoodyBiomassDensity``

### ISSUE THREAD

**Issue by pioneerHitesh** [microsoft/torchgeo#1679]
### Description

There is an ``urllib.error.HTTPError: HTTP Error 500: Internal Server Error`` occuring . This issue occures when compiling from github and installing using pip3. It is occuring for`` AbovegroundLiveWoodyBiomassDensity`` which is a module from ``torchgeo.datasets.agb_live_woody_density``

### Steps to reproduce

python
``
from torchgeo.datasets.agb_live_woody_density import AbovegroundLiveWoodyBiomassDensity 
ALWBD = AbovegroundLiveWoodyBiomassDensity(paths="~/test", download=True)
``

### Version

0.6.0.dev0 and 0.5.0

**Comment by adamjstewart** [comment]
@nilsleh you added this dataset, do you remember where you got the download link from? Probably just needs to be updated.
