### ISSUE TITLE
Add BigEarthNet

### ISSUE THREAD

**Issue by calebrob6** [microsoft/torchgeo#168]
I think we should add BigEarthNet (http://bigearth.net/):
- EO dataset with over 100 citations
- Used in immediately related work https://arxiv.org/pdf/1911.06721.pdf
- It is included in the Tensorflow datasets (https://www.tensorflow.org/datasets/catalog/bigearthnet)

**Comment by isaaccorley** [comment]
This is a duplicate I think: https://github.com/microsoft/torchgeo/issues/63
