### ISSUE TITLE
Inline code link display in trainer tutorial

### ISSUE THREAD

**Issue by ashnair1** [microsoft/torchgeo#170]
Inline code links aren't rendered properly in the docs.  See `TropicalCycloneWindEstimation` under [Lightning modules](https://torchgeo.readthedocs.io/en/latest/tutorials/trainers.html#Lightning-modules) and `Trainer` under [Training](https://torchgeo.readthedocs.io/en/latest/tutorials/trainers.html#Training).

Not sure if there is an automatic way to handle this.

**Comment by adamjstewart** [comment]
Good catch. I'm guessing this is a bug in nbsphinx. I removed the in-line code formatting in https://github.com/microsoft/torchgeo/commit/5d4ad430d28fe20728533645a5cee8ce27dfa47b to workaround this for now.
