### ISSUE TITLE
Add licenses to datasets/pre-trained weights tables

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#1710]
### Issue

TorchGeo is entirely under the MIT license. But the datasets and pre-trained weights that users download with TorchGeo are all under different licenses. For some users—especially in industry—these licenses are actually very important.

### Fix

We should collect license information on all datasets/models and add them to our documentation tables. The files to add these to in TorchGeo are the `*.csv` files in `docs/api`.

**Comment by robmarkcole** [comment]
To clarify this would add a `License` column to each csv? 
Is there a preferred list of strings to use for the license ID? If not suggest aligning on the strings used either on Github (shorter list) or Huggingface (more expansive list, screenshot below):

<img width="249" alt="image" src="https://github.com/microsoft/torchgeo/assets/11855322/a7cec879-e945-41cd-ae0a-941338575ae9">
