### ISSUE TITLE
OnDiskDataset not robust to multiprocessing

### ISSUE THREAD

**Issue by fredtony** [microsoft/torchgeo#1765]
### Description

To start, I love the addition of OnDiskDataset!

However, when using OnDiskDataset for processing a very large dataset, I decided that it would only be feasible to use this class with some multiprocessing to create the dataset and I figured that the SQLite backend would be safe for multiprocessing. As I tried it out, I found that it failed most of the time. Sample code is provided below that causes a failure most times it is run with the error `sqlite3.IntegrityError: UNIQUE constraint failed: OnDiskDataset.id`. Try/except loops also fail because it locks the database after 1 of these failures and nothing can be written after this.

I believe that this is because in the `extend` method, it is creating arbitrary ids based on the previous database size and so there is a race condition on the ids being inserted into the database. I believe this could be resolved by allowing the db to insert its own ids when not specified (i.e. the ids are an optional arg and are not used to insert unless provided explicitly).

I'd be happy to get a PR up for that if it would be helpful.

### Steps to reproduce

The following code fails frequently when the machine has multiple cores but may occasionally pass (failure is due to a race condition on the indices being written.
```
from multiprocessing import Pool
from functools import partial
import torch
from torch_geometric.data import OnDiskDataset
from torch_geometric.utils import from_smiles


def process_and_extend_data_chunk(
    smiles_list: list[str], dataset: OnDiskDataset
) -> None:
    data_list = []
    for smiles in smiles_list:
        data = from_smiles(smiles)
        data.y = torch.rand((1, 5))
        data_list.append(data)
    dataset.extend(data_list)


def main():
    my_dataset = OnDiskDataset(root="test_data")
    smiles_list = [
        [
            "CC",
            "CCC",
        ],
        [
            "CCCC",
            "CCCCC",
        ],
        [
            "CCCCCC",
            "CCCCCCC",
        ],
        [
            "CCCCCCCC",
            "CCCCCCCCC",
        ],
        [
            "CCCCCCCCCC",
            "CCCCCCCCCCC",
        ],
        [
            "CCCCCCCCCCCC",
            "CCCCCCCCCCCCC",
        ],
        [
            "CCCCCCCCCCCCCC",
            "CCCCCCCCCCCCCCC",
        ],
    ]
    partial_process_and_extend_data_chunk = partial(
        process_and_extend_data_chunk, dataset=my_dataset
    )
    with Pool() as p:
        p.map(partial_process_and_extend_data_chunk, smiles_list)


if __name__ == "__main__":
    main()
```

### Version

2.4.0

**Comment by calebrob6** [comment]
Hey @fredtony, I'm glad you like it! Unfortunately, I don't think we can take any credit because I think you are using https://github.com/pyg-team/pytorch_geometric and not torchgeo :) (this is a library for working with geographic data -- satellite imagery, etc.)

**Comment by fredtony** [comment]
> Hey @fredtony, I'm glad you like it! Unfortunately, I don't think we can take any credit because I think you are using https://github.com/pyg-team/pytorch_geometric and not torchgeo :) (this is a library for working with geographic data -- satellite imagery, etc.)

Apologies, meant to add the issue to `torch_geometric`!
