### ISSUE TITLE
Add instructions on downloading the DeepGlobeLandCover dataset

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1797]
### Issue

The [dataset](https://torchgeo.readthedocs.io/en/stable/api/datasets.html#torchgeo.datasets.DeepGlobeLandCover) docs state `The dataset that we use with a custom train/test split can be downloaded from Kaggle` - however this is a necessity as you cannot pass `download=True`

### Fix

Suggest documenting the steps using kaggle  CLI (below), or just to state that this must be performed? Alternatively host on Huggingface and automate the download

```
pip install kaggle # place api key at ~/.kaggle/kaggle.json
cd data
kaggle datasets download -d geoap96/deepglobe2018-landcover-segmentation-traindataset
unzip deepglobe2018-landcover-segmentation-traindataset.zip
```

**Comment by adamjstewart** [comment]
> Alternatively host on Huggingface and automate the download

We haven't yet found the license for the dataset, so I'm not sure if we can do this. Want to try to reach out to the authors of the dataset to see? If the license permits redistribution, I'll add it to our Hugging Face account.

**Comment by robmarkcole** [comment]
Reading the [paper](https://arxiv.org/pdf/1805.06561.pdf), appears the imagery is from deepglobe/maxar, will check my network for contacts there

**Comment by robmarkcole** [comment]
RE license, I came to a dead end - the people I spoke to who had worked on the dataset have all moved on

As to updating the docs, I think it could be useful if you could clarify what level of detail we should be providing?

**Comment by adamjstewart** [comment]
https://torchgeo.readthedocs.io/en/stable/api/datasets.html#torchgeo.datasets.SSL4EOS12 is an example of a similar dataset where users have to manually download it. So a similar level of detail is fine. Want to submit a PR?
