### ISSUE TITLE
NCCM checksum error

### ISSUE THREAD

**Issue by favyen2** [microsoft/torchgeo#1854]
### Description

NCCM dataset with download=True, checksum=True fails with checksum error, because the zip file seems to be created by the server on-the-fly.

### Steps to reproduce

Code:

```python
from torchgeo.datasets import NCCM
NCCM(download=True, checksum=True, paths="./data/nccm/")
```

Error:

```
Downloading https://figshare.com/ndownloader/articles/13090442/versions/1 to ./data/nccm/13090442.zip
RuntimeError: File not found or corrupted.
```

It seems the zip file changes each time so the md5 is different.

```
$ md5sum file1.zip
eb29f8e5b6f41ed2c32ba5ed2b0bdc90  file1.zip
$ md5sum file2.zip
179c53feddaa81c609b0cd0433db669a  file2.zip
$ head -c 14 file1.zip | hd
00000000  50 4b 03 04 0a 00 08 08  00 00 c9 8b 45 58        |PK..........EX|
0000000e
$ head -c 14 file2.zip | hd
00000000  50 4b 03 04 0a 00 08 08  00 00 a0 8c 45 58        |PK..........EX|
0000000e
```
According to https://stackoverflow.com/questions/67902342/how-to-read-zip-file-header-manually the last four bytes there indicate file modification time. (Other bytes are different too though.) So it is possible the server is generating the zip files on the fly.

### Version

0.6.0.dev0 (a52f88f614400513cb6ef432c7caa7a8c46d878f)

**Comment by adamjstewart** [comment]
This is annoying. Luckily NCCM is CC-BY-4.0. We should probably rehost the dataset on HF and download it from there instead so the checksum is stable.

**Comment by adamjstewart** [comment]
@shreyakannan1205 @yichiac do we already have a copy of NCCM downloaded somewhere? How big is it? I can upload it to HF (or show you how) and then we can change the download URL/checksum, should be simple.

**Comment by yichiac** [comment]
I have the downloaded NCCM on my local machine. The size is ~2.4GB. 

I agree with @favyen2. The zip has only five files (three TIF masks and two GEE codes). The checksums for all individual files are the same, regardless of the download time. 

We can also consider downloading only mask files using separate links instead of the whole zip file.

**Comment by adamjstewart** [comment]
5 files isn't bad, although it does open up the possibility of a zip bomb if we first extract the zip file before checksumming. But we already default to skipping the checksum, and TorchGeo isn't a security-focused application, so I'm not too worried.

I'm fine with either:

1. Download 1 zip file, extract, checksum 3 mask files
2. Download 3 mask files, checksum 3 mask files

Who wants to submit the PR?

**Comment by yichiac** [comment]
I will submit a PR for this issue today.
