### ISSUE TITLE
Unpin torch, use a min or range?

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1895]
### Summary

I'm experiencing dependency conflicts when using torchgeo in a larger ecosystem, due to the pinning of torch. I appreciate the reasons for doing so (ref https://github.com/microsoft/torchgeo/issues/544) but propose a more flexible approach, ideally specifying a minimum version

### Rationale

Dependency hell in complex codebase

**Comment by robmarkcole** [comment]
Perhaps I misunderstood but aren't all requirements in [required.txt](https://github.com/microsoft/torchgeo/blob/main/requirements/required.txt) pinned?
I am on `torchgeo==0.5.1 & torch==2.1.0` but eyeing torchgeo 0.6 which has `torch==2.2.0` which is quite new

**Comment by isaaccorley** [comment]
Those requirements are used for CI and tests. The dependencies are listed in pyproject.toml.

**Comment by robmarkcole** [comment]
Thanks for the clarification @issaca 
Apologies for the confusion on my part
