### ISSUE TITLE
Errors & improvements in Metrics descriptions

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#1923]
### Description

- In segmentation trainer, configure_metrics, Multiclass Jaccard Index (IoU) is described as using macro but it is using micro
- In classification, MultiLabelClassificationTask, OA mentions pixels, but it should refer to image level metrics such as true and false positive
- Regression metrics cannot take macro/micro as args, perhaps we remove the Note to avoid confusion
- Detection, MeanAveragePrecision computes many metrics. Run the example at https://github.com/Lightning-AI/torchmetrics/blob/master/examples/detection_map.py returns

```
0s
result
{'map': tensor(0.6000),
 'map_50': tensor(1.),
 'map_75': tensor(1.),
 'map_small': tensor(-1.),
 'map_medium': tensor(-1.),
 'map_large': tensor(0.6000),
 'mar_1': tensor(0.6000),
 'mar_10': tensor(0.6000),
 'mar_100': tensor(0.6000),
 'mar_small': tensor(-1.),
 'mar_medium': tensor(-1.),
 'mar_large': tensor(0.6000),
 'map_per_class': tensor(-1.),
 'mar_100_per_class': tensor(-1.),
 'classes': tensor(0, dtype=torch.int32)}
```

- Note, outside the scope of this issue, but we do not pass [dist_sync_on_step](https://lightning.ai/docs/torchmetrics/stable/pages/overview.html#advanced-metric-settings) - we could and default to False, but allow setting true for distributed training with Lightning

CC @jdilger

### Steps to reproduce

NA

### Version

dev

**Comment by adamjstewart** [comment]
We had to delay the release until today so we actually still have time to include this if someone quickly opens a PR.

**Comment by robmarkcole** [comment]
I would love to but once my kids are up, my plate is full for the day!
