### ISSUE TITLE
Switch from SMP to TorchSeg

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#1967]
### Summary

We should consider switching from SMP to TorchSeg for our segmentation models.

### Rationale

SMP is [no longer maintained](https://github.com/qubvel/segmentation_models.pytorch/issues/849). TorchSeg is a fork providing important features we need:

* Support for modern versions of timm
* Support for ViT backends
* Fewer dependencies
* Better CI

### Implementation

Should be a simple `s/segmentation_models_pytorch/torchseg/g`.

However, there are a few more things I would like to see in TorchSeg before committing to the switch:

* Dependabot used to manage all dependencies, especially timm
* Minimum version testing, especially timm

These are things I can set up myself when I have time (hopefully soon!)

### Alternatives

I have not yet found a better alternative to SMP.

If SMP becomes maintained once again, we could contribute back all of the improvements in TorchSeg. But I find this unlikely, and I like the control we have over TorchSeg if we need to quickly add new features.

### Additional information

@isaaccorley I'm opening this issue to make sure I don't forget to do this before the 0.6 release sometime in April.

**Comment by isaaccorley** [comment]
I can work on figuring out why dependabot and codecov wasn't working. I'll also try running some tests with different version of timm to see what happens.

**Comment by adamjstewart** [comment]
Seems like SMP is now maintained, we just need to start contributing PRs there instead of to TorchSeg.
