### ISSUE TITLE
v0.5.2 missing PRs

### ISSUE THREAD

**Issue by DimitrisMantas** [microsoft/torchgeo#1980]
### Description

The source code for the v0.5.2 release is missing *at least* the #1898 PR. I haven't checked for other omissions.

### Steps to reproduce

1. Run ``pip install torchgeo==0.5.2 --force-reinstall`` and navigate to ``torchgeo.trainers.SemanticSegmentationTask``.

### Version

0.5.2

**Comment by adamjstewart** [comment]
Since #1898 introduces a new feature (`loss='jaccard'` now supports `ignore_index`), it was decided that it would be included in the next feature release (0.6.0), not in the next bug fix release (0.5.2). TorchGeo follows [semver](https://semver.org/) when deciding which release includes which PRs.

**Comment by DimitrisMantas** [comment]
Clear, thanks!
