### ISSUE TITLE
Git clone and pip install results in 'Successfully installed UNKNOWN-0.0.0'

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#2056]
### Description

As title, it is installed but cannot be imported due to being UNKNOWN

### Steps to reproduce

I am in a docker container.
```
git clone https://github.com/microsoft/torchgeo.git
cd torchgeo
pip install .
```

Trace: 
```
root@2e5af809535b:/opt/projects/torchgeo# pip install .
Processing /opt/projects/torchgeo
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1788 sha256=790bd9cdb17fb4aea2f15ca5fe7f8724aeb8c4396fbaf70a64967ca69785a408
  Stored in directory: /tmp/pip-ephem-wheel-cache-udn8olvx/wheels/ab/2c/a0/a7e77a489e21bffde7d78e5a039123dc6589d9fde03ad6c2e3
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```

### Version

main

**Comment by adamjstewart** [comment]
I'm not able to reproduce this with pip 23.0 and setuptools 63.4.3. Can you check what setuptools version you're using? We may need to increase the minimum version required.

**Comment by adamjstewart** [comment]
I suspect that this is the same issue as https://github.com/serge-sans-paille/pythran/pull/2196 and we simply need to bump to setuptools 62+, but would like to confirm before fixing.

**Comment by adamjstewart** [comment]
I'm able to confirm this issue with setuptools 60, but not with setuptools 61.

**Comment by robmarkcole** [comment]
I have `types-setuptools==69.1.0.20240310`

**Comment by adamjstewart** [comment]
What about setuptools?

**Comment by adamjstewart** [comment]
Also try a newer pip if you can.

**Comment by robmarkcole** [comment]
```
setuptools.__version__
65.5.0

pip 22.0.2
```

**Comment by robmarkcole** [comment]
Upgraded to `pip 24.0` and now `Successfully installed torchgeo-0.6.0.dev0`

```
>>> import torchgeo
>>> torchgeo.__version__
'0.6.0.dev0'
```

**Comment by adamjstewart** [comment]
Interesting. Could be related to https://github.com/pypa/setuptools/issues/3269 (a system Python installation interfering with pip's build isolation). Unfortunately we don't have an easy way to check or control the pip version used to install torchgeo. If you're happy now that the install works, I think we can close this. If not, you might have to report something to pip themselves and ask when/where the issue was fixed.

**Comment by robmarkcole** [comment]
Happy to close. I added `RUN pip install --upgrade pip` to the dockerfile now :)
