### ISSUE TITLE
CLI script for test

### ISSUE THREAD

**Issue by yichiac** [microsoft/torchgeo#2082]
### Issue

The current documentation for testing is:
`torchgeo test --config config.yaml --trainer.ckpt_path=...`

It would return:
`error: Unrecognized arguments: --trainer.ckpt_path=...`

### Fix

It shuold be
`torchgeo test --config config.yaml ckpt_path=...`

**Comment by adamjstewart** [comment]
You are correct. Want to submit a PR?

**Comment by TropicolX** [comment]
Hi @adamjstewart, I submitted a PR for this here: #2091
