### ISSUE TITLE
PatternNet download link is broken

### ISSUE THREAD

**Issue by burakekim** [microsoft/torchgeo#2093]
### Description

[PatterNet dataset](https://torchgeo.readthedocs.io/en/stable/_modules/torchgeo/datasets/patternnet.html#PatternNet) [download link ](https://drive.google.com/file/d/127lxXYqzO6Bd0yZhvEbgIfz95HaEnr9K) is broken.

It seems it is officially hosted [here](https://nuisteducn1-my.sharepoint.com/:u:/g/personal/zhouwx_nuist_edu_cn/EYSPYqBztbBBqS27B7uM_mEB3R9maNJze8M1Qg9Q6cnPBQ?e=MSf977). Was someone mirroring it on a personal Google Drive? 

### Steps to reproduce

```
from torchgeo.datasets import PatternNet

patternet = PatternNet(root='./', transforms=None, download=True, checksum=True)
```

### Version

0.5.2

**Comment by adamjstewart** [comment]
That URL can't be downloaded automatically, seems to require manual clicking.

Personally, I would try to reach out to the author and ask what license the dataset is distributed under. If it allows redistribution, we can rehost it on Hugging Face and make it much easier to download.

**Comment by burakekim** [comment]
Just sent an email asking about the license and whether we can host it on HF!
