### ISSUE TITLE
Figure plotting with Eurosat & classification trainer gives blank images

### ISSUE THREAD

**Issue by robmarkcole** [microsoft/torchgeo#2139]
### Description

As title:

![image](https://github.com/microsoft/torchgeo/assets/11855322/d8590ca9-93f2-46bd-9afa-29f5b18058ef)

### Steps to reproduce

```python
datamodule = EuroSATDataModule(batch_size=64, num_workers=8, bands=EuroSAT.BAND_SETS["all"])
datamodule.setup(stage="fit")

task = ClassificationTask(
    model="resnet18",
    in_channels=13,
    num_classes=10,
    loss="ce",
    lr=0.001,
)

logger = TensorBoardLogger("tb_logs", name="my_eurosat")

trainer = L.Trainer(
    max_epochs=10,
    logger=logger
)
trainer.fit(task, datamodule)
```

### Version

master

**Comment by robmarkcole** [comment]
Appears the issue is not with the basic plotting:

![image](https://github.com/microsoft/torchgeo/assets/11855322/c7c7e78c-b1e5-4bc7-9202-26fa9c130545)

**Comment by adamjstewart** [comment]
I'm guessing this is related to #1263? That is, dataset plotting works, but data module plotting (in which data augmentation has been applied) does not? The solution for this dataset is the same as for all other datasets where this issue occurs, and is described in #1263.

**Comment by robmarkcole** [comment]
Noted this is likely effecting many datasets and due to the norm. Closing and continuing on the linked issue
