### ISSUE TITLE
BigEarthNet download links are broken

### ISSUE THREAD

**Issue by burakekim** [microsoft/torchgeo#2171]
### Description

The [Sentinel-2](https://github.com/microsoft/torchgeo/blob/7de473d058e0db8c41831efae7015d354a796f34/torchgeo/datasets/bigearthnet.py#L254) and [Sentinel-1](https://github.com/microsoft/torchgeo/blob/7de473d058e0db8c41831efae7015d354a796f34/torchgeo/datasets/bigearthnet.py#L260) download links appear to be broken.

### Steps to reproduce

```
from torchgeo.datasets import BigEarthNet

dataset = BigEarthNet(root='data', split='train', bands='all', num_classes='19', transforms=None, download=True, checksum=True)
```

### Version

0.6.0.dev0

**Comment by calebrob6** [comment]
Looks like the download links on https://bigearth.net/ changed to point to
zenodo -- want to open a PR (and check the checksums of the new files)?

**Comment by adamjstewart** [comment]
They just released BigEarthNet v2, right? Is v1 still available to download? Would be neat to add a new `version` parameter that lets you choose which version you want, although that's obviously more work.

**Comment by burakekim** [comment]
I am on it!
