### ISSUE TITLE
check Rwanda Fields dataset and tests

### ISSUE THREAD

**Issue by darkblue-b** [microsoft/torchgeo#2261]
### Description

check if Rwanda Field Boundary dataset is broken

### Steps to reproduce

inspect code base

### Version

a637f56d..ccc314cd

**Comment by adamjstewart** [comment]
I double checked and it turns out that it isn't broken. I was iterating through the dataset and looking for good plots and the dataset crashed when I tried to load the 14th sample. It turns out the test set only has 13 samples. False alarm!
