### ISSUE TITLE
ETCI2021 Img/Label pairing

### ISSUE THREAD

**Issue by calebrob6** [microsoft/torchgeo#231]
I think there might be a bug based on visualizing some of the training patches. Shown below are VV, VH, Water mask, Flood mask for some sample:

![image](https://user-images.githubusercontent.com/1088078/141015608-4b3182af-4d78-4c44-9c13-77c13ae2eefe.png)

Run the following a few times to reproduce:
```
from torchgeo.datasets import ETCI2021

import numpy as np
import matplotlib.pyplot as plt

ds = ETCI2021("data/", split="train", download=False)

for i in np.random.choice(len(ds), size=10, replace=False):
    
    img1 = np.rollaxis(ds[i]["image"][:3].numpy(),0,3)
    img2 = np.rollaxis(ds[i]["image"][3:].numpy(),0,3)
    mask1 = ds[i]["mask"][0].numpy()
    mask2 = ds[i]["mask"][1].numpy()
        
    fig, axs = plt.subplots(1,4,figsize=(12,3))
    axs[0].imshow(img1)
    axs[0].axis("off")
    axs[1].imshow(img2)
    axs[1].axis("off")
    axs[2].imshow(mask1)
    axs[2].axis("off")
    axs[3].imshow(mask2)
    axs[3].axis("off")
    plt.tight_layout()
    plt.show()
    plt.close()
```

@adamjstewart -- this is another example of a dataset that will need a custom trainer. You can interpret the imagery as a 6 band input, however there are two label masks (you want to predict the flood mask, and you are always given the water mask).

**Comment by adamjstewart** [comment]
> this is another example of a dataset that will need a custom trainer.

I'm not sure I understand. To me this sounds like a 7 channel input (image + water mask) and a 1 channel target (flood mask). Can this not be handled by the Dataset/DataModule?

**Comment by calebrob6** [comment]
> I'm not sure I understand. To me this sounds like a 7 channel input (image + water mask) and a 1 channel target (flood mask). Can this not be handled by the Dataset/DataModule?

The flood mask is currently passed as a mask, you _could_ pass it as an input.

**Comment by calebrob6** [comment]
The problem above is caused by glob.glob not returning files in sorted order and is fixed by putting `sorted(...)` everywhere.  I'm going to commit this fix directly to main.

**Comment by calebrob6** [comment]
E.g. of correct pairing:

![image](https://user-images.githubusercontent.com/1088078/141017881-66cfa35a-9890-442b-a492-ebd112789947.png)

**Comment by adamjstewart** [comment]
Adding reference to commit that fixed this: 2e4b203666eb3df36c051dd9d71496e64f726550

We should backport this to 0.1.1 when we create that release.

**Comment by calebrob6** [comment]
Moving forward, let's visualize what comes out of a dataset before we merge them. These semantic bugs are the real killers.

**Comment by adamjstewart** [comment]
Can you add a `plot` method to the dataset? I think that's something we should consider requiring for all future datasets.

**Comment by isaaccorley** [comment]
This one is my fault for not checking via plotting. Thanks @calebrob6 for the fix. Will verify with plots in the future.

**Comment by liecn** [comment]
Hi,

Sorry to bother you. But I do have a training problem when using this dataset. Thanks so much for your time.

https://github.com/microsoft/torchgeo/discussions/745#discussion-4345898

**Comment by isaaccorley** [comment]
> Hi,
> 
> Sorry to bother you. But I do have a training problem when using this dataset. Thanks so much for your time.
> 
> [#745 (comment)](https://github.com/microsoft/torchgeo/discussions/745#discussion-4345898)

@liecn Kindly only leave comments on closed issues if they are relevant.
