### ISSUE TITLE
Missing Band information for pretrained weights

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#2364]
### Issue

The [satlas weights](https://github.com/microsoft/torchgeo/blob/67fe198c78128e1162a241a783ac20ce350b52db/torchgeo/models/resnet.py#L527) have a `bands` entry in the metadata that lists the order and bands, for consistency and common api, it would be helpful to have that same metadata entry for all the other weights as well.

### Fix

Add `bands` info to metadata.

@paolofraccaro

**Comment by InderParmar** [comment]
I am eager to work on this issue, can you please assign this issue to me?

**Comment by nilsleh** [comment]
Thanks @InderParmar looking forward to the PR.

**Comment by InderParmar** [comment]
@adamjstewart , @nilsleh  Is it possible for you to add the "hacktoberfest" label to this issue.

**Comment by adamjstewart** [comment]
Done

**Comment by InderParmar** [comment]
> Done

Hi @adamjstewart , sorry to bother you again, Actually as I am participating in Hacktoberfest, they also require the "Hacktoberfest-accepted" label to be there, whileI am working on the issue, can you please add it for me.

**Comment by InderParmar** [comment]
Hi @nilsleh , @adamjstewart , 

I have implemented the following changes as per the request in issue #2364:

1. **Added Consistent `bands` Metadata**:
   - Updated `resnet.py` and `vit.py` to include consistent `bands` metadata for each weight.
   - Imported `_satlas_bands`, `_satlas_sentinel2_bands`, and `_satlas_landsat_bands` from `swin.py` to ensure uniformity across models.

2. **Reformatted Imports**:
   - Ensured the import blocks are properly sorted and formatted to comply with linting requirements.

3. **Passed CI Tests**:
   - All CI tests, including linting and formatting checks, have now passed successfully.
If there are no further changes required, can you close this issue by adding the "hacktoberfest-accepted" label to the Pull Request. 
Please let me know if there are further changes required. Thank you!
