### ISSUE TITLE
Add FTW Datamodule

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#2365]
### Summary

@calebrob6 I would like to use the FTW datasets for some experiments, and saw that there is a `DataModule` in the [FTW-repo](https://github.com/fieldsoftheworld/ftw-baselines/blob/main/src/ftw/datamodules.py) which essentially looks already like a torchgeo datamodule. Wondering if it is possible to add this here as well? I can also open a PR for this.

**Comment by calebrob6** [comment]
Yeah of course! I just didn't do it in my initial PR because I didn't want to take the time to figure out the tests

**Comment by nilsleh** [comment]
Cool, will open the PR later today.
