### ISSUE TITLE
Add Annual NLCD Datasets

### ISSUE THREAD

**Issue by giswqs** [microsoft/torchgeo#2386]
### Summary

MRLC has released the annual NLCD data products (1985-2023). See [here](https://www.mrlc.gov/data?f%5B0%5D=category%3ALand%20Cover&f%5B1%5D=project_tax_term_term_parents_tax_term_name%3AAnnual%20NLCD).

The download URL looks like this:

```python
year = 2023 # any year between 1985 and 2023
url = f"https://s3-us-west-2.amazonaws.com/mrlc/Annual_NLCD_LndCov_{year}_CU_C1V0.tif"
```

The current torchgeo NLCD dataset look like this:
https://torchgeo.readthedocs.io/en/stable/api/datasets.html#nlcd

```python
url = 'https://s3-us-west-2.amazonaws.com/mrlc/nlcd_{}_land_cover_l48_20210604.zip'

md5s: ClassVar[dict[int, str]] = {
    2001: '538166a4d783204764e3df3b221fc4cd',
    2006: '67454e7874a00294adb9442374d0c309',
    2011: 'ea524c835d173658eeb6fa3c8e6b917b',
    2016: '452726f6e3bd3f70d8ca2476723d238a',
    2019: '82851c3f8105763b01c83b4a9e6f3961',
}
```

Should we update the NLCD class to use the annual NLCD data products or create another NLCD class like `AnnualNLCD`?

**Comment by adamjstewart** [comment]
I vote for updating the current class. There was also some interest in the other NLCD products, I think someone has a WIP PR. Feel free to submit a PR for some or all of this.
