### ISSUE TITLE
ChesapeakeCVPR Base SubDataset: Download Link Broken

### ISSUE THREAD

**Issue by arjunarao619** [microsoft/torchgeo#2390]
### Description

The download link for the base subdataset in `ChesapeakeCVPR` dataset returns a 403. Permalink to affected code:

https://github.com/microsoft/torchgeo/blob/05ea5138fd9bbf995a6c51505c7a54c6c351ea8d/torchgeo/datasets/chesapeake.py#L340C1-L343C6

This could potentially be due to a missing `.sign(...)` to access planetary computer resources. A new, working Azure link for the dataset is available here: `https://lilawildlife.blob.core.windows.net/lila-wildlife/lcmcvpr2019/cvpr_chesapeake_landcover.zip`. 

### Steps to reproduce

```
states = ['de', 'md', 'va', 'wv', 'pa', 'ny']
spl =  [f'{state}-train' for state in states]
spl.extend([f'{state}-val' for state in states])
spl.extend([f'{state}-test' for state in states])

ChesapeakeCVPR(
root='/share/chesapeake', 
download=True, 
layers=['naip-new','naip-old','landsat-leaf-on','landsat-leaf-off','nlcd','lc','buildings','prior_from_cooccurrences_101_31_no_osm_no_buildings'], 
splits=spl
) 
```

### Version

0.7.0.dev0

**Comment by adamjstewart** [comment]
Want to open a PR to fix this?
