### ISSUE TITLE
Switch ETCI2021 to use MLHub when it is released on MLHub

### ISSUE THREAD

**Issue by calebrob6** [microsoft/torchgeo#240]
Radiant Earth is going to put ETCI2021 in early 2022. When this happens we should switch the implementation to use data from there as it will give us the test set labels too.

**Comment by adamjstewart** [comment]
The only downside of this is that it requires an API key so it's a little extra work to use.

**Comment by adamjstewart** [comment]
I don't think this ever happened, did it? Seems like MLHub is dead, we can prob close this.
