### ISSUE TITLE
EuroSAT Dataset 403 Download Error

### ISSUE THREAD

**Issue by isaiahlg** [microsoft/torchgeo#2424]
### Description

I'm trying to download the EuroSAT dataset, and I'm getting a 403 Forbidden HTTP error.

![Image](https://github.com/user-attachments/assets/12933968-c0b7-4cf7-abfb-eeda4a397a55)

### Steps to reproduce

1. Ensure you have a directory where the EuroSAT dataset is not already downloaded
2. Run the following line of code to download the EuroSAT dataset: `dataset = EuroSAT("path/to/data", download=True)` with `path/to/data` set to the empty directory from step 1
3. You should see the .zip file download, but then you'll get the following error before the .txt files download:

![Image](https://github.com/user-attachments/assets/626349c0-ac88-4938-895a-c567f5f69807)

### Version

0.6.1

**Comment by isaaccorley** [comment]
Seems like it was able to download the images but not the files containing the splits. These were the splits from the In Domain Representation Learning paper hosted by the authors from Google. Let me see if I have them stored anywhere and I'll rehost them to HuggingFace.

**Comment by adamjstewart** [comment]
I think the only reason we didn't originally host those on HF was due to an unknown license, but I doubt Google would care about these files.

**Comment by adamjstewart** [comment]
UC Merced is also affected by this.

**Comment by adamjstewart** [comment]
https://github.com/google-research/google-research/issues/2287

**Comment by tameTNT** [comment]
I was able to get the notebook ([colab link if you would like to do it yourself](https://colab.research.google.com/github/google-research/google-research/blob/master/remote_sensing_representations/rsr_datasets.ipynb)) to work and generate the files. I've attached the ones for EuroSAT and UC Merced (the two mentioned) for anyone who runs into this issue before they fix the storage bucket/link issue - hope that helps!

[eurosat-test.txt](https://github.com/user-attachments/files/17921600/eurosat-test.txt)
[eurosat-train.txt](https://github.com/user-attachments/files/17921601/eurosat-train.txt)
[eurosat-val.txt](https://github.com/user-attachments/files/17921602/eurosat-val.txt)

[uc_merced-test.txt](https://github.com/user-attachments/files/17921626/uc_merced-test.txt)
[uc_merced-train.txt](https://github.com/user-attachments/files/17921625/uc_merced-train.txt)
[uc_merced-val.txt](https://github.com/user-attachments/files/17921624/uc_merced-val.txt)

**Comment by adamjstewart** [comment]
Commented on the other issue too, these splits are different from the original version. Not sure if the script properly sets random seeds, so it may be impossible to generate the exact same split unless someone has the old files lying around somewhere.

**Comment by tameTNT** [comment]
As luck would have it, on the machine I'm now on I do actually have them lying around from downloading the datasets earlier last month. I didn't realise the generated ones would be different, apologies for the earlier confusion.

[eurosat-train.txt (original)](https://github.com/user-attachments/files/17933101/eurosat-train.txt)
[eurosat-val.txt (original)](https://github.com/user-attachments/files/17933100/eurosat-val.txt)
[eurosat-test.txt (original)](https://github.com/user-attachments/files/17933102/eurosat-test.txt)

[uc_merced-train.txt (original)](https://github.com/user-attachments/files/17933104/uc_merced-train.txt)
[uc_merced-val.txt (original)](https://github.com/user-attachments/files/17933106/uc_merced-val.txt)
[uc_merced-test.txt (original)](https://github.com/user-attachments/files/17933105/uc_merced-test.txt)

**Comment by adamjstewart** [comment]
YES! I can confirm these are the original splits for EuroSAT (I'll trust you on UC Merced). I'll upload these to our HF account and fix the TorchGeo data loaders.
