### ISSUE TITLE
About opencv

### ISSUE THREAD

**Issue by ashnair1** [microsoft/torchgeo#259]
When LandCover.ai dataset was added in cbea03e, opencv was added as a dependency but it doesn't seem to be used anywhere in torchgeo. Is it required?

**Comment by adamjstewart** [comment]
The LandCover.ai dataset is distributed as a collection of large image tiles and a list of smaller patches for the train/val/test split. It comes with a `split.py` script used to generate these patches, and this script uses OpenCV. We could write our own script using PIL, but I think it's easier to just use their script, which requires OpenCV.

**Comment by ashnair1** [comment]
Ah I see. Makes sense 👍
