### ISSUE TITLE
RUnning colab says stack_samples not found

### ISSUE THREAD

**Issue by kaushikCanada** [microsoft/torchgeo#274]
![image](https://user-images.githubusercontent.com/21248009/145479770-6eb12522-c10e-425d-ae6a-408111cfe38e.png)

**Comment by adamjstewart** [comment]
This is a feature that was introduced in main but hasn't yet made it into a release. You can either change the `pip install` to install from the main branch or run the tutorial for the last release.

I'm not sure what the best way to handle this is. We want the tutorials to install a stable release from pip, but we also want to update the tutorials when things change. I think the solution is to figure out why RtD isn't giving us stable release versions and to default to those. I'll look into this over the next week.

**Comment by adamjstewart** [comment]
I think I've got this fixed now. The docs should now default to a stable release. You can still view the latest docs if you want to, but you have to manually switch to those.

**Comment by adamjstewart** [comment]
This is only partially fixed. Although the docs display the notebook for the stable release, the "Open in Colab" button always opens the version from `main`.
