### ISSUE TITLE
Sample in pixel units, not CRS units

### ISSUE THREAD

**Issue by RitwikGupta** [microsoft/torchgeo#279]
Related to #278, once our datasets are projected to UTM with fixed `xres` and `yres`, I want to sample a set amount of pixels, say `1024 x 1024`. Current samplers sample in the unit of the CRS (in this case meters). Therefore, I have to set the sample size to `desired_chip_size / xres_yres_of_imagery`. While this works, a flag which lets the user choose which unit to sample in would be great.

**Comment by calebrob6** [comment]
I'm fine with adding this as a feature -- this is especially annoying with datasets in units of degrees (we do this here https://github.com/microsoft/torchgeo/blob/main/benchmark.py#L143)

**Comment by RitwikGupta** [comment]
Perhaps you can help me understand what the intended behavior is, based on that benchmark. When passing a `size` to the sampler, does it give you a patch that is `(size, size)` pixels large (so a Tensor that is `[1, 1, size, size]`), or is the intended behavior that it will give you a patch that is `(size / res, size / res)` pixels large?

Currently, I am getting the latter behavior (which seems to be the intended one.

```python
from datasets import WatchRaster
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from torchgeo.samplers import RandomGeoSampler
from torchgeo.datasets import stack_samples
import torch

ds = WatchRaster()
print(f'Dataset resolution: {ds.res}')
sampler = RandomGeoSampler(ds, size=512, length=5)
dl = DataLoader(ds, sampler=sampler, collate_fn=stack_samples)

for sample in dl:
    image = sample['image']
    print(image.shape)
```

```
Dataset resolution: 2.4
torch.Size([1, 1, 214, 214])
torch.Size([1, 1, 214, 214])
torch.Size([1, 1, 214, 214])
torch.Size([1, 1, 213, 213])
torch.Size([1, 1, 213, 213])
```

The proposed change could be to modify `get_random_bounding_box` in utils to add a `pixelspace` boolean flag. This would change `maxx` and `maxy` to be `minx + t_size[1] * res`.

**Comment by calebrob6** [comment]
Yes, latter behavior is correct, and proposed change is correct! We may want to think about how we name the args in the samplers, options:
- mutually exclusive `size_in_pixels` and `size_in_crs_units` args
- `size` arg and `pixelspace` flag

**Comment by RitwikGupta** [comment]
I like former better. Make it a required arg so that the user is forced to choose. What's the voting process for these changes? @adamjstewart

**Comment by RitwikGupta** [comment]
The former can be implemented as an enum to make it explicit in the code. `sampler(sample_mode=utils.SIZE_IN_PIXELS)`

**Comment by adamjstewart** [comment]
I feel like there was a reason I originally chose to do things in CRS units, but I can't remember what that reason was. I'm fine with whatever. We could just only support sampling in pixel units.
