### ISSUE TITLE
Sentinel2 Dataset filename_glob not fully extensible

### ISSUE THREAD

**Issue by KennSmithDS** [microsoft/torchgeo#290]
**Description of Issue** 
When attempting to use the Sentinel2 Dataset class, I am receiving an error that no Sentienl2 data was found in the root directory provided. This didn't work in either the parent data directory containing both features and labels, nor the sub-directories for each type. 

Upon digging into the source code, the Sentinel2 Dataset class expects the raster filenames to comply with Sentinel2 naming convention:

`filename_blob = "T*_*_B02_*m.*"`

The files in the dataset I have been provided via the DrivenData.org competition has raster files named with just the {band}.tif, e.g. B02.tif, B03.tif. Therefore no .tif data is found in the root directory and the program throws the FileNotFoundError below:

```
Traceback (most recent call last):
  File "/home/ying/cloud_cover_competition/library_experiment.py", line 15, in <module>
    load_dataset(ROOT_PATH, CLOUD_BANDS)
  File "/home/ying/cloud_cover_competition/library_experiment.py", line 10, in load_dataset
    cloud_dataset = Sentinel2(root=path, bands=bands)
  File "/home/ying/anaconda3/envs/torch/lib/python3.9/site-packages/torchgeo/datasets/sentinel.py", line 100, in __init__
    super().__init__(root, crs, res, transforms, cache)
  File "/home/ying/anaconda3/envs/torch/lib/python3.9/site-packages/torchgeo/datasets/geo.py", line 251, in __init__
    raise FileNotFoundError(
FileNotFoundError: No Sentinel2 data was found in '/home/ying/cloud_cover_competition/data/'
```

**Steps to Reproduce**

1. Dataset download instructions accessible through the DrivenData.org portal or directly from AzureBlobStorage, respectively:

- https://www.drivendata.org/competitions/83/cloud-cover/data/
- https://cloudcoverdatacentralus.blob.core.windows.net/public?se=2022-08-01T12%3A00Z&sp=rl&sv=2018-11-09&sr=c&sig=Bhyvh/jgnWKtcBbZ62nOJKalUByIzDikBenFxLJs7FU%3D

2. Run a Python script like in attached image
![torchgeo_dataloader_error](https://user-images.githubusercontent.com/30271891/146247103-02655a13-18e9-4dda-acdc-c53f9935737c.png)

**Expected Behavior**
Sentientl2 Dataset loader should be extensible with unconventional filenames to find GeoTIFF files if the band number is in the filename:

- B02.tif
- B03.tif
- B04.tif
- B08.tif
- etc...

**Comment by KennSmithDS** [comment]
As an interim solution, I made a class that extends the base Sentinel2 class, and overrode the `filename_glob` and `filename_regex` properties:

![custom_sentinel2_class](https://user-images.githubusercontent.com/30271891/146249997-4e3bd476-934c-4f67-96e1-1e21f65689e8.png)

**Comment by calebrob6** [comment]
Thanks for the thorough issue @KennSmithDS!

I think letting users specify unconventional filenames directly in the Sentinel2 dataset would be messy. Instead, I think the best way to do this is to create a new Dataset that extends Sentinel2 or RasterDataset as illustrated in a new example notebook that @RitwikGupta is creating in https://github.com/microsoft/torchgeo/pull/283.

**Comment by adamjstewart** [comment]
It sounds like this confusion has been resolved, but if you have any other questions let me know!
