### ISSUE TITLE
Running into TypeError - unexpected keyword argument 'checksum' in custom LightningDataModule 

### ISSUE THREAD

**Issue by KennSmithDS** [microsoft/torchgeo#302]
**Description of Issue**
I have tried to implement my custom LightningDataModule for the Cloud Cover Detection Competition Dataset with the SemanticSegmentationTask from torchgeo.trainers using both `cyclone.py` and `so2sat.py` as templates.

The [TypeError](https://github.com/KennSmithDS/drivendata_cloud_competition/blob/cb01d27972a9ce83bc70f204ad241e6927e7a2db/cloud.py#L175) is occuring when I try to call `trainer.fit()` in cell 181 of [this](https://github.com/KennSmithDS/drivendata_cloud_competition/blob/ac49e2fa872d113c4103b8aa919dc35bf6d14cd9/cloud.py#L181) Jupyter Notebook.

Digging into the torchgeo source code, I see that both the VisionDataset and RasterDataset are base classes extending the PyTorch Dataset class. Both `cyclone.py` and `so2sat.py` include a default parameter of `checksum=False`, so I tried adding that to Sentinel2CloudCover class to no avail. It seems that the class extension to the Sentinel2CloudCover dataset isn't supporting/expecting the checksum argument.

Appreciate any help in troubleshooting this!

**Class Inheritance Tree**
torch.utils.data.Dataset (base)
   - GeoDataset
      - RasterDataset
         - Sentinel
            - Sentinel2
               - Sentinel2CloudCover

**Screenshot**
![CloudCoverDataModule_TypeError](https://user-images.githubusercontent.com/30271891/146626006-f35578f1-c5b1-48a2-8df9-ebd8e84370b6.png)

**Error Traceback**
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_11127/4274221884.py in <module>
----> 1 lightning_trainer.fit(model=semseg_task, datamodule=cloud_module)

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, train_dataloader, ckpt_path)
    735             )
    736             train_dataloaders = train_dataloader
--> 737         self._call_and_handle_interrupt(
    738             self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    739         )

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    680         """
    681         try:
--> 682             return trainer_fn(*args, **kwargs)
    683         # TODO: treat KeyboardInterrupt as BaseException (delete the code below) in v1.7
    684         except KeyboardInterrupt as exception:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    770         # TODO: ckpt_path only in v1.7
    771         ckpt_path = ckpt_path or self.resume_from_checkpoint
--> 772         self._run(model, ckpt_path=ckpt_path)
    773 
    774         assert self.state.stopped

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1124 
   1125         # hook
-> 1126         self._data_connector.prepare_data()
   1127 
   1128         # ----------------------------

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py in prepare_data(self)
    152                 )
    153             if (dm_prepare_data_per_node and local_rank_zero) or (not dm_prepare_data_per_node and global_rank_zero):
--> 154                 self.trainer.datamodule.prepare_data()
    155         # handle lightning module prepare data:
    156         # check for prepare_data_per_node before calling lightning_module.prepare_data

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/core/datamodule.py in wrapped_fn(*args, **kwargs)
    472                 )
    473             else:
--> 474                 fn(*args, **kwargs)
    475 
    476         return wrapped_fn

~/cloud_cover_competition/cloud.py in prepare_data(self)
    172         This includes optionally downloading the dataset. This is done once per node,
    173         while :func:`setup` is done once per GPU.
--> 174         """
    175         Sentinel2CloudCover(
    176             self.root_dir,

TypeError: __init__() got an unexpected keyword argument 'checksum'
```

**Comment by KennSmithDS** [comment]
Closing issue, must have been a caching issue after I added the checksum argument to the Sentinel2CloudCover class. I killed the Jupyter Lab server and rebooted the environment, this error was gone.

**Comment by isaaccorley** [comment]
Glad you figured it out. Just wanted to mention that inheriting from Sentinel2, and further RasterDataset, generally is used in combination with one of our GeoSamplers. However, since you implemented your own getitem method which takes an integer index, this would be considered a VisionDataset because you're not using the geospatial information to perform sampling.

The cyclone and so2sat datasets both inherit from VisionDataset and we use the checksum to optionally compare the md5s of downloaded data to validate that it's not corrupt.

**Comment by KennSmithDS** [comment]
@isaaccorley 

Would you recommend me inheriting VisionDataset directly, instead of the chain of classes from Sentinel2>Sentinel>RasterDataset?

Also, I am using the custom `__getitem__()` function because the dataset is provided with a metadata CSV which then is modified in the notebook to get the filepath to each GeoTiff for the four bands provided (2,3,4,8). Is it better to pass just the rootdir property to the custom Dataset object, and then have it find the files based on the directory structure, instead of using a dataframe which has string filepaths to each individual band and mask for a chip?

I am getting all kinds of other errors now still when calling the .fit(), which makes me feel it doesn't like the way the filepaths are being passed to the Dataset from the DataModule. Thoughts?

Cheers

**Comment by calebrob6** [comment]
I would definitely recommend `VisionDataset` for a dataset that contains pre-made patches of imagery which it sounds like this dataset is.

Sketch of what I would do:
- Pass the path to the CSV to the constructor of the Sentinel2CloudCover Dataset
- Figure out where all the filenames are in the constructor and make something like `self.fns = [...]` that contains the path to each patch (or each band of each patch)
- Have `__getitem__(self, idx)` load and concatenate the data from the filenames pointed to by `self.fns[idx]`

**Comment by isaaccorley** [comment]
I would also make sure that your getitem returns a dict with at least "image" and "mask" keys. That is what the SemanticSegmentationTask grabs to feed to the model. In your code it looks like you are calling this "chip" and "label" which won't work. Also note that the image should be float and the mask should be int32 to work with the loss fns.
