### ISSUE TITLE
FCN model should be removed

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#318]
We have a simple fully-connected network model in TorchGeo. However, this model is not specific to geospatial data. We should see if any other library has an FCN implementation we can use, and if not contribute one. TorchGeo should only contain datasets/models/transforms for geospatial data; we want to keep our scope focused.

**Comment by calebrob6** [comment]
I doubt any of the architectures in `torchgeo.models` are specific to geospatial data -- I don't know what a geospatial data specific model looks like. The models that are currently implemented are all used in geospatial data applications. The FCN specifically was useful in https://www.grss-ieee.org/community/technical-committees/2021-ieee-grss-data-fusion-contest-track-msd/.

**Comment by adamjstewart** [comment]
We discussed this and decided to try to contribute this to segmentation_models_pytorch if they're willing to accept it.

**Comment by adamjstewart** [comment]
https://github.com/qubvel/segmentation_models.pytorch/issues/527

**Comment by adamjstewart** [comment]
It seems like the authors of segmentation_models_pytorch are not interested in adding our FCN implementation. I guess we can keep it in TorchGeo for now.
