### ISSUE TITLE
detect_anomaly not supported for pytorch-lightning<1.5

### ISSUE THREAD

**Issue by ashnair1** [microsoft/torchgeo#347]
Support for passing `detect_anomaly` (in `conf/defaults.yaml`) was added in pytorch-lightning 1.5 (Refer PyTorchLightning/pytorch-lightning#9848). For lower versions training will fail with 

```
Traceback (most recent call last):
  File "/home/ashwin/Desktop/Projects/torchgeo/train.py", line 226, in <module>
    main(conf)
  File "/home/ashwin/Desktop/Projects/torchgeo/train.py", line 196, in main
    trainer = pl.Trainer(**trainer_args)
  File "/home/ashwin/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'detect_anomaly'
```
So we either need to pin minimum version to 1.5 or remove this flag from `conf/defaults.yaml`.

**Comment by adamjstewart** [comment]
@calebrob6 would you be opposed to simply removing `conf/defaults.yaml`? I think it's useful for documenting which values can be set, but it currently pins us to the latest version of pytorch-lightning if we don't want to ignore deprecation warnings.

**Comment by calebrob6** [comment]
Yeah we should definitely get rid of it

**Comment by adamjstewart** [comment]
@ashnair1 want to submit a PR to do this? If not I'll get to it when working on #227.

**Comment by ashnair1** [comment]
I can do it. To clarify, the `conf/defaults.yaml` and any reference to it in `train.py` needs to be removed correct?

**Comment by adamjstewart** [comment]
Yep!
