### ISSUE TITLE
No dockerfile for torchgeo

### ISSUE THREAD

**Issue by MATRIX4284** [microsoft/torchgeo#367]
there is no docker images for torchgeo

**Comment by adamjstewart** [comment]
What would be the benefit of having a Docker image for TorchGeo? Most software, especially Python libraries, isn't distributed via Docker. We already have source code and wheels available on PyPI, and support package managers like pip/conda/spack. TorchGeo itself is pure-Python, so as long as you have one of the aforementioned package managers installed, you can easily install TorchGeo.

If we did provide Docker images, we would need to provide them for many OSes, CUDA versions, and Python versions. I don't see a benefit of this over package managers. But I don't use Docker heavily other than for reproducing bugs, so please correct me if I'm wrong.

**Comment by MATRIX4284** [comment]
i added this because I tried to install torchgeo in my OS 4 times but was unable to import datasets when trying to run with Jupyter.Later on i came to know that is happening as i need to set my PROJ_LIB to the correct one before i run the jupyter.
To ease the usability while using open source jupyter to download datsets  and visualize torcheo outputs the idea of torchgeo docker was provided.
It will enable the users to quickly get the environment with torchgeo up and running to use with jupyter notebook without needing to go for much OS isssues by trying to install on bare OS .This is enable more people in geospatial community to adapt torchgeo.
Moreover going forward geospatial will be used n cloud where containerization will play an important and anyhow people need to dockerize first to use torchgeo within micro-services framework.Again in that case this docker wil come as a useful feature.

**Comment by adamjstewart** [comment]
> Later on i came to know that is happening as i need to set my PROJ_LIB to the correct one before i run the jupyter.

Yes, I've actually encountered this same issue myself. Package managers like Spack and Conda [explicitly set this for you](https://github.com/spack/spack/blob/v0.17.1/var/spack/repos/builtin/packages/proj/package.py#L111,L117). If you're having problems with pip, I would suggest using a more powerful package manager like Spack or Conda. Pip isn't designed to install non-Python dependencies.

From what I can tell, the issue you reported is specific to PROJ and has nothing to do with TorchGeo. Maybe it would make more sense to add a Dockerfile to the PROJ library?

**Comment by adamjstewart** [comment]
Closing as it doesn't sound like this is a feature we really need in TorchGeo.
