### ISSUE TITLE
Add support for float type raster datasets

### ISSUE THREAD

**Issue by tritolol** [microsoft/torchgeo#379]
I'm trying to load a custom DSM raster dataset of type float32.

I'm implementing a new class based on RasterDataset like so:
```
from torchgeo.datasets import RasterDataset

class DsmData(RasterDataset):
    filename_glob = "*.tif"
```

When I call `__getitem__()` on a DsmData object, I get an array containing int32 data instead.
I traced this down to the following line in the RasterDataset definition
https://github.com/microsoft/torchgeo/blob/3f7e525fbd01dddd25804e7a1b7634269ead1760/torchgeo/datasets/geo.py#L464

All raster datasets are forced into the int32 type which should not happen.

Having RasterDatasets with different types will probably cause problems when applying union or intersection operations.
But since a custom `collate_fn` can be defined, the user is able to provide a solution for this.

I achieved the desired behavior simply by removing the mentioned line.

**Comment by calebrob6** [comment]
Oof, good catch. We should definitely change this. Do you want to open a PR to get this started?

**Comment by adamjstewart** [comment]
> Having RasterDatasets with different types will probably cause problems when applying union or intersection operations.

Nope, this won't be a problem. All of our collation functions use torch operators that can handle various dtypes:
```console
$ python
>>> import torch
>>> a = torch.zeros(3, 3, dtype=torch.int32)
>>> b = torch.zeros(3, 3, dtype=torch.float32)
>>> torch.stack((a, b))
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
>>> torch.maximum(a, b)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
>>> torch.cat((a, b))
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
```

**Comment by tritolol** [comment]
Created PR #384
