### ISSUE TITLE
Getting RGB images from EuroSAT

### ISSUE THREAD

**Issue by Pangoraw** [microsoft/torchgeo#396]
Hi!

In some datasets, it seems the bands can be selected when constructing but this not the case for EuroSAT. How can one get the normalized RGB images (similar to [`eurosat/rgb`](https://www.tensorflow.org/datasets/catalog/eurosat#eurosatrgb_default_config) version in tensorflow_datasets) ?

**Comment by adamjstewart** [comment]
Related to #289, @nilsleh might be interested in this
