### ISSUE TITLE
CBF dataset and Vector Dataset ValueError

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#399]
I was looking at the cbf dataset, specifically just using the British Columbia data and encountered `ValueError: No valid geometry objects found for rasterize`. Looking at the VectorDataset class, this occurs when the shapes list is empty, meaning that the query finds a hit for a file, but there are no geometries that survive the filtering based on the query, and then 
`masks = rasterio.features.rasterize(
            shapes, out_shape=(int(height), int(width)), transform=transform
        )` 
fails.

**Comment by adamjstewart** [comment]
Not entirely sure what to do about this. I guess we could check to see if `shapes` is empty and return a Tensor of all "nodata" pixel values in this case? Is that a reliable way to determine the background value?
