### ISSUE TITLE
CDL dataset error

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#423]
When calling `ds = CDL(root, download=True)`, the following error occurs: `rasterio._err.CPLE_AppDefinedError: The transformation is already "north up" or a transformation between pixel/line and georeferenced coordinates cannot be computed for ./data/cdl/2020_30m_cdls.tif.ovr. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.` 
I think this occurs because `filename_glob = "*_30m_cdls.*"` also picks up the other files such as `_30m_cdls.tif.ovr` which are part of the dataset.

**Comment by calebrob6** [comment]
Does changing `filename_glob = "*_30m_cdls.tif"` fix it?

**Comment by nilsleh** [comment]
Yes, but the documentation of `RasterDataset`states that file extension should not be included.
