### ISSUE TITLE
GridGeoSampler may never reach end of image

### ISSUE THREAD

**Issue by remtav** [microsoft/torchgeo#431]
In ran into this issue after running multiple tests and double-checking why my inference script using GridGeoSampler never reached the end (right and bottom) of an image. 

I'm using GridGeoSampler with an image of size 1591 x 2187 pixels, a chip size of 512 and stride of 256. For the sake of clarity, let's just say my image is 600 x 600 (pixel units or crs units doesn't matter here -> just assume minimum bounds in x and y are 0 if you're thinking crs units):

I want GridGeoSampler to sample my 600 x 600 image in chips of 512x512, with a stride of 256. 
The total number of row and columns [as calculated in the \_\_init__ and \_\_iter_ of GridGeoSampler](https://github.com/microsoft/torchgeo/blob/main/torchgeo/samplers/single.py#L198) will be:
rows = columns = (600 - 512) // 256 +1 = 1

Therefore, the \_\_iter__ function will use two for loops [with range(rows)](https://github.com/microsoft/torchgeo/blob/main/torchgeo/samplers/single.py#L205) and range (columns). Since those two variables are 1, only 1 512x512 sample will be returned by the sampler, thus ignoring 88 (600-512) pixels of width and height where valid values existed in my image.

To adapt the current implementation, I believe rows and columns should be calculated this way:
( image width - chip size + stride size ) // stride size + 1
or in the code, for rows:
`rows = int((bounds.maxy - bounds.miny - self.size[0] + self.stride[0]) // self.stride[0]) + 1`

**Comment by adamjstewart** [comment]
As a result of #376, GridGeoSampler will also skip areas smaller than the patch size entirely.

I think the issue you reported is easy to fix, we just have to be careful not to go out of bounds of the image. So the minx/miny will need to be adjusted with a smaller stride for the last sample per row/col.

**Comment by remtav** [comment]
> As a result of #376, GridGeoSampler will also skip areas smaller than the patch size entirely.
> 
> I think the issue you reported is easy to fix, we just have to be careful not to go out of bounds of the image. So the minx/miny will need to be adjusted with a smaller stride for the last sample per row/col.

Hadn't though of the "smaller stride at the end of image" solution. I guess this ensures the chip_size is respected and could definitely work. The only drawback is that this changes the expected behaviour of the sampler since the stride may not always be the size that was initially set. If a user (like me :) )  is stitching inference chips into a large array assuming the stride is constant (let's say he's using pixel units from #279 ), the result of the "smaller stride at the end of image" solution may be surprising. If this solution is chosen, I guess the user will have to make sure he/she is not naively assuming the stride will always be constant and make sure to rely on the bbox information returned by the sampler either directly from the __iter__ function of the sampler of from a __getitem__ as in [RasterDataset](https://github.com/microsoft/torchgeo/blob/6bc3779907ef4a92952763ef338a471425bcce36/torchgeo/datasets/geo.py#L432).

An alternative that I'd consider is to keep a constant stride, but return a sample that is truncated, leaving it to the user to use a pad_to function [as is done in test_transforms on the Chesapeake dataset](https://github.com/microsoft/torchgeo/blob/744078fcff7e48957ffa5d0cd6b8acf3f5767b0a/torchgeo/datamodules/chesapeake.py#L256).

In both cases, I'd issue a warning since either the stride's value or the sample_size's value as inputted by the user will be forced to change at the righter and lower limit of an image.

**Comment by adamjstewart** [comment]
Also see #30. Part of the reason that GeoDatasets return the CRS and bbox is so you can stitch things back together easily even if the stride changes for the last image. Of course, we still need to actually write stitching utilities to use this information.

**Comment by calebrob6** [comment]
Thanks a ton for the bug report @remtav!

Here's a notebook that gives a self-contained example of:
- running a model on a RasterDataset made up of a single tile with GridGeoSampler
- stitching the results together in the inference loop
- visualizing the input/output

https://gist.github.com/calebrob6/7b226eb73877187f85fb5e1621bb7971 

![image](https://user-images.githubusercontent.com/1088078/155824198-aa587e37-2659-41e8-ba8e-e1628bbbce8e.png)

![image](https://user-images.githubusercontent.com/1088078/155824215-fb98caf7-82ce-45f2-9ed2-a96c4dd65b7e.png)

There is definitely something wrong here, but I haven't parsed it yet.
