### ISSUE TITLE
Some plotting tests actually plot

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#436]
I noticed that some of our plotting tests actually result in a plot being opened and displayed. We should fix this. Also, some of our plotting tests are missing `plt.close()` so might leak too many file handles.

**Comment by adamjstewart** [comment]
It looks like `plt.show()` is coming from `torchgeo/datasets/geo.py` and will be removed once we either remove `plot()` or update it to the new API. However, we are definitely still missing a `plt.close()` is many dataset plotting tests. Pinging @nilsleh since they've added a lot of plotting code.

**Comment by nilsleh** [comment]
So the plotting tests should all have a plt.close() after the plotting method is called?

**Comment by adamjstewart** [comment]
Correct, this prevents file handle leaks.
