### ISSUE TITLE
[Feature Request] Object Detection Trainer

### ISSUE THREAD

**Issue by austinmw** [microsoft/torchgeo#442]
Hi, I'm curious if there are any plans to add an object detection trainer?

Also, I wonder how feasible it may be to extend this library to work with video data and multi-object tracking tasks? Or is torchvideo more appropriate for this task?

**Comment by adamjstewart** [comment]
> Hi, I'm curious if there are any plans to add an object detection trainer?

I would love to see this. We already have many object detection and instance segmentation datasets (NWPU VHR-10 was the very first dataset I added). I don't personally have the time to add one at the moment, but if you have the time to contribute a PR I would love to review it.

> Also, I wonder how feasible it may be to extend this library to work with video data and multi-object tracking tasks? Or is torchvideo more appropriate for this task?

I would scope TorchGeo as a library for any kind of geospatial data, especially image/video data. So if the datasets you have in mind involve multispectral (or RGB) satellite imagery and time series data, I think TorchGeo would be a great fit. Torchvideo (and torchvision) are more for non-geospatial RGB images/videos.

**Comment by adamjstewart** [comment]
Preliminary work on this in #758
