### ISSUE TITLE
Bug: missing "not" operator to set ignore_zeros in segmentation trainer

### ISSUE THREAD

**Issue by remtav** [microsoft/torchgeo#444]
I believe there's a bug in the translation from ignore_zeros to ignore_index in the [\_\_init__ of SemanticSegmentationTask](https://github.com/microsoft/torchgeo/blob/c933694ddc9a121af9415389949aefcc84760472/torchgeo/trainers/segmentation.py#L89).
`self.ignore_zeros = None if kwargs["ignore_zeros"] else 0` should be:
`self.ignore_zeros = None if kwargs["ignore_zeros"] is None else 0` as is done [when define loss function](https://github.com/microsoft/torchgeo/blob/c933694ddc9a121af9415389949aefcc84760472/torchgeo/trainers/segmentation.py#L57)

`self.ignore_zeros` is later used to define the "self.ignore_index" of the self.train_metrics. For sake of clarity, I'd suggest renaming it to  `self.ignore_index` directly in the \_\_init__. 

Therefore, this
```
...
        self.ignore_zeros = None if kwargs["ignore_zeros"] else 0

        self.config_task()

        self.train_metrics = MetricCollection(
            [
                Accuracy(
                    num_classes=self.hparams["num_classes"],
                    ignore_index=self.ignore_zeros,
...
```
would become
```
...
        self.ignore_index = None if kwargs["ignore_zeros"] is None else 0

        self.config_task()

        self.train_metrics = MetricCollection(
            [
                Accuracy(
                    num_classes=self.hparams["num_classes"],
                    ignore_index=self.ignore_index,
...
```
If you'd like, I can definitely push a PR for to fix this bug if the solution seems ok to all. Let me know.

**Comment by adamjstewart** [comment]
@calebrob6 were you the one who wrote this logic? Can you take a look at this?

**Comment by calebrob6** [comment]
@remtav, the problem with defining this in __init__ is that nn.CrossEntropLoss uses -1000 as a "None" value (https://github.com/microsoft/torchgeo/blob/c933694ddc9a121af9415389949aefcc84760472/torchgeo/trainers/segmentation.py#L57). Some changes that I think make sense:
- Add an assert to make sure `kwargs["ignore_zeros"]` is boolean
- Throw an error if `kwargs["ignore_zeros"] == True` and `loss="jaccard"` (as the jaccard loss doesn't have an `ignore_index`)
- Say that it should be a boolean in the docstring

**Comment by adamjstewart** [comment]
@calebrob6 can you submit a PR for this? I'll include it in 0.2.1 (releasing this week).

**Comment by calebrob6** [comment]
@adamjstewart aiming this for 0.3
