### ISSUE TITLE
Sentinel2 Class not behaving as expected

### ISSUE THREAD

**Issue by graceebc9** [microsoft/torchgeo#447]
Hello!

I am working with the Sentinel2 class. I have updated the class to deal with a different data format when downloaded from google cloud. (.SAFE data format, with Geo-JPEG2000 for the bands) 

when trying to plot the individual bands, they are all coming out as identical, I am trying to get the individual bands to use in NDVI indice

```python
class Sentinel(RasterDataset):
    """Abstract base class for all Sentinel datasets.

    `Sentinel <https://sentinel.esa.int/web/sentinel/home>`_ is a family of
    satellites launched by the `European Space Agency (ESA) <https://www.esa.int/>`_
    under the `Copernicus Programme <https://www.copernicus.eu/en>`_.

    If you use this dataset in your research, please cite it using the following format:

    * https://asf.alaska.edu/data-sets/sar-data-sets/sentinel-1/sentinel-1-how-to-cite/
    """


class Sentinel2(Sentinel):
    """Sentinel-2 dataset.

    The `Copernicus Sentinel-2 mission
    <https://sentinel.esa.int/web/sentinel/missions/sentinel-2>`_ comprises a
    constellation of two polar-orbiting satellites placed in the same sun-synchronous
    orbit, phased at 180° to each other. It aims at monitoring variability in land
    surface conditions, and its wide swath width (290 km) and high revisit time (10 days
    at the equator with one satellite, and 5 days with 2 satellites under cloud-free
    conditions which results in 2-3 days at mid-latitudes) will support monitoring of
    Earth's surface changes.
    """

    # TODO: files downloaded from USGS Earth Explorer seem to have a different
    # filename format than the official documentation
    # https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-2-msi/naming-convention
    # https://sentinel.esa.int/documents/247904/685211/Sentinel-2-MSI-L2A-Product-Format-Specifications.pdf
    filename_glob = "T*.jp2"
    # filename_regex = r"""
    #     ^T(?P<tile>\d{2}[A-Z]{3})
    #     _(?P<date>\d{8}T\d{6})
    #     _(?P<band>B[018][\dA])
    #     _(?P<resolution>\d{2}m)
    #     \..*$
    # """
    date_format = "%Y%m%dT%H%M%S"

    # https://gisgeography.com/sentinel-2-bands-combinations/
    all_bands = [
        "B01",
        "B02",
        "B03",
        "B04",
        "B05",
        "B06",
        "B07",
        "B08",
        "B8A",
        "B09",
        "B10",
        "B11",
        "B12",
    ]
    RGB_BANDS = ["B04", "B03", "B02"]

    separate_files = True
    def __init__(
        self,
        root: str = "data",
        crs: Optional[CRS] = None,
        res: Optional[float] = None,
        bands: Sequence[str] = [],
        transforms: Optional[Callable[[Dict[str, Any]], Dict[str, Any]]] = None,
        cache: bool = True,
    ) -> None:
        """Initialize a new Dataset instance.

        Args:
            root: root directory where dataset can be found
            crs: :term:`coordinate reference system (CRS)` to warp to
                (defaults to the CRS of the first file found)
            res: resolution of the dataset in units of CRS
                (defaults to the resolution of the first file found)
            bands: bands to return (defaults to all bands)
            transforms: a function/transform that takes an input sample
                and returns a transformed version
            cache: if True, cache file handle to speed up repeated sampling

        Raises:
            FileNotFoundError: if no files are found in ``root``
        """
        self.bands = bands if bands else self.all_bands

        super().__init__(root, crs, res, transforms, cache)


    def plot(  # type: ignore[override]
        self,
        sample: Dict[str, Tensor],
        show_titles: bool = True,
        suptitle: Optional[str] = None,
    ) -> plt.Figure:
            """Plot a sample from the dataset.

            Args:
                sample: a sample returned by :meth:`RasterDataset.__getitem__`
                show_titles: flag indicating whether to show titles above each panel
                suptitle: optional string to use as a suptitle

            Returns:
                a matplotlib Figure with the rendered sample

            Raises:
                ValueError: if the RGB bands are not included in ``self.bands``

            .. versionadded:: 0.3
            """
            rgb_indices = []
            for band in self.RGB_BANDS:
                if band in self.bands:
                    rgb_indices.append(self.bands.index(band))
                else:
                    raise ValueError("Dataset doesn't contain some of the RGB bands")

            image = sample["image"][rgb_indices].permute(1, 2, 0)
            image = torch.clamp(image / 3000, min=0, max=1)  # type: ignore[attr-defined]

            fig, ax = plt.subplots(1, 1, figsize=(4, 4))

            ax.imshow(image)
            ax.axis("off")

            if show_titles:
                ax.set_title("Image")

            if suptitle is not None:
                plt.suptitle(suptitle)

            return fig
```

I have two folders with jp2 band data 

```python
#path contains four .jp2 files for the four bands, path8 only contains band8
path = '/Users/gracecolverd/Documents/Fire_Proj/sentinel2/S2A_MSIL1C_20160911T092032_N0204_R093_T35UNU_20160911T092026.SAFE/GRANULE/L1C_T35UNU_A006382_20160911T092026/IMG_DATA'
path8 = '/Users/gracecolverd/Documents/Fire_Proj/sentinel2/S2A_MSIL1C_20160911T092032_N0204_R093_T35UNU_20160911T092026.SAFE/GRANULE/L1C_T35UNU_A006382_20160911T092026/IMG_DATA/b8'
````

when I try to look at individual bands they are all coming back the same 

```python
ds = Sentinel2(path, bands=['B02', 'B03' , 'B04', 'B08'])

sampler = RandomGeoSampler(ds, size=1024, length=1)
dl = DataLoader(ds, sampler=sampler, collate_fn=stack_samples)

fig, ax = plt.subplots(3, figsize = (10,10) )

for sample in dl:
      print('count')
      image = sample['image']
      print(image.shape)
      image = torch.squeeze(image)
      print(image)
      ax[0].imshow(image[0])
      ax[1].imshow(image[1])
      ax[2].imshow(image[2])
```

The image is tensor 4 deep as expected with the four bands, but all the tensors are the same 
```
torch.Size([1, 4, 102, 102])
tensor([[[2473, 2428, 2356,  ..., 2941, 2987, 2998],
         [2337, 2431, 2436,  ..., 2873, 2901, 2962],
         [2364, 2485, 2395,  ..., 2831, 2910, 2945],
         ...,
         [2353, 2389, 2388,  ..., 2799, 2784, 2449],
         [2582, 2600, 2580,  ..., 2687, 2499, 1956],
         [2795, 2802, 2711,  ..., 2195, 1849, 1642]],

        [[2473, 2428, 2356,  ..., 2941, 2987, 2998],
         [2337, 2431, 2436,  ..., 2873, 2901, 2962],
         [2364, 2485, 2395,  ..., 2831, 2910, 2945],
         ...,
         [2353, 2389, 2388,  ..., 2799, 2784, 2449],
         [2582, 2600, 2580,  ..., 2687, 2499, 1956],
         [2795, 2802, 2711,  ..., 2195, 1849, 1642]],

        [[2473, 2428, 2356,  ..., 2941, 2987, 2998],
         [2337, 2431, 2436,  ..., 2873, 2901, 2962],
         [2364, 2485, 2395,  ..., 2831, 2910, 2945],
         ...,
         [2353, 2389, 2388,  ..., 2799, 2784, 2449],
         [2582, 2600, 2580,  ..., 2687, 2499, 1956],
         [2795, 2802, 2711,  ..., 2195, 1849, 1642]],

        [[2473, 2428, 2356,  ..., 2941, 2987, 2998],
         [2337, 2431, 2436,  ..., 2873, 2901, 2962],
         [2364, 2485, 2395,  ..., 2831, 2910, 2945],
         ...,
         [2353, 2389, 2388,  ..., 2799, 2784, 2449],
         [2582, 2600, 2580,  ..., 2687, 2499, 1956],
         [2795, 2802, 2711,  ..., 2195, 1849, 1642]]], dtype=torch.int32)
```
The image that is returned is 
![New Note](https://user-images.githubusercontent.com/91670329/156400693-002f7f83-4dd1-4ac5-a440-3a75b2dcbc40.jpeg)

I can't attach the JP2 files but the files I used were B2, B3, B4, B8 from 

S2A_MSIL1C_20160911T092032_N0204_R093_T35UNU_20160911T092026.SAFE

**Comment by adamjstewart** [comment]
Can you tell me more about the filename and directory hierarchy? `RasterDataset` has a number of class attributes you can define: https://github.com/microsoft/torchgeo/blob/v0.2.0/torchgeo/datasets/geo.py#L268,L298

The most important ones for you will be `filename_glob`, `filename_regex`, `date_format`, and `separate_files`. Hopefully the docstrings for each attribute are somewhat useful, but basically:

* `filename_glob`: used to search for files (or rather, to exclude files that might not be part of this dataset)
* `filename_regex`: used to extract relevant metadata from the filename, such as band number of timestamp
* `date_format`: format of the datetime string extracted from the filename
* `separate_files`: whether all bands are stored in a single file or in separate files

Currently `filename_glob` and `filename_regex` only support filenames, they don't support directories. So if each band is stored in a separate file but the rest of the metadata like datetime is stored in a higher directory, this won't work.

**Comment by graceebc9** [comment]
all of the files are in the same directory - the  filename_glob : filename_glob = "T*.jp2" catches them all 

![Today at 1555](https://user-images.githubusercontent.com/91670329/156443232-ce630733-f35b-4bd4-bb58-b7114164f89e.jpeg)

**Comment by graceebc9** [comment]
I will try updating the filename_regrex - thanks

**Comment by graceebc9** [comment]
Ive added the     filename_regex = r"""
    ^T(?P<tile>\d{2}[A-Z]{3})
    _(?P<date>\d{8}T\d{6})
    _(?P<band>B[018][\dA])
    \..*$
"""

Now when I try and run my plotter I get the following error with the output of the data loader 

IndexError                                Traceback (most recent call last)
/var/folders/n5/_2d3c5sd5j3810327mknn0sh0000gn/T/ipykernel_14970/3782857617.py in <module>
      2 
      3 
----> 4 for sample in dl:
      5 
      6     image = sample['image']

~/opt/miniconda3/envs/test_tor/lib/python3.9/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

~/opt/miniconda3/envs/test_tor/lib/python3.9/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    559     def _next_data(self):
    560         index = self._next_index()  # may raise StopIteration
--> 561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    562         if self._pin_memory:
    563             data = _utils.pin_memory.pin_memory(data)

~/opt/miniconda3/envs/test_tor/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

~/opt/miniconda3/envs/test_tor/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

~/opt/miniconda3/envs/test_tor/lib/python3.9/site-packages/torchgeo/datasets/geo.py in __getitem__(self, query)
    421                             end = match.end("resolution")
    422                             filename = filename[:start] + "*" + filename[end:]
--> 423                     filepath = glob.glob(os.path.join(directory, filename))[0]
    424                     band_filepaths.append(filepath)
    425                 data_list.append(self._merge_files(band_filepaths, query))

IndexError: list index out of range

**Comment by adamjstewart** [comment]
Is your filename glob still `"T*.jp2"`? I think you'll want something like `"T*B02.jp2"` so you don't accidentally pick up the same scene multiple times (once per band). This is what we do for the `Landsat` dataset as well.

**Comment by graceebc9** [comment]
thank you so much that worked! 

Is there a way to confirm which band is which? I plotted ndvi based on if the bands were ordered 2,3,4,8 but it looks a little funky. (although I do need to normalise the bands)
![New Note](https://user-images.githubusercontent.com/91670329/156448656-6063c48f-2ff7-4cd2-b037-806813f1517e.jpeg)

I want to apply the indices class like in the tutorial colab before feeding into my model- do you know think it would be acceptable to apply it to the samples as they are sampled rather than applying as part of the class / preprocessing? 

Thank you so much for your help I have been going round in circles on this all day!

**Comment by adamjstewart** [comment]
> Is there a way to confirm which band is which?

The bands should be in the same order as `bands`. If you want to confirm this, you could try to manually sample data from the image using rasterio and make sure that the pixel values match. But I'm pretty confident that this should work correctly.

> I plotted ndvi based on if the bands were ordered 2,3,4,8 but it looks a little funky. (although I do need to normalise the bands)

Maybe double check which bands you're using to compute NDVI (should be 4 and 8) and try a better colormap? Normalization should definitely help though, I would set vmin and vmax to be 0 to 1, otherwise the plot will vary based on the min/max of that particular image. https://custom-scripts.sentinel-hub.com/custom-scripts/sentinel-2/ndvi/ has some good explanations of the meaning of the values.

> I want to apply the indices class like in the tutorial colab before feeding into my model

My personal take on this is that the spectral bands themselves already capture the same information so adding an additional NDVI band wouldn't provide much benefit. I think NDVI is great for plotting and dimensionality reduction/feature extraction but less useful in deep learning where your first layer already does feature extraction automatically.

> do you know think it would be acceptable to apply it to the samples as they are sampled rather than applying as part of the class / preprocessing?

Yes, all transforms can either be applied during sampling on an image-by-image basis (by passing them in when defining the dataset class) or after sampling on an entire batch at a time. I actually prefer the latter since it allows you to perform the transform on the GPU instead of the CPU. The former is only useful when things are CPU-bound and you want to do them in parallel.

**Comment by graceebc9** [comment]
thanks! confirmed that the bands work in the order as expected -the issue was normalising. thanks also for the insights re. the indices - we've taken those onbord
