### ISSUE TITLE
ETCI 2021 dataset plotting issues

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#462]
I think there's something wrong with how we're plotting ETCI 2021 data:
```console
$ python
>>> import matplotlib.pyplot as plt
>>> from torchgeo.datasets import ETCI2021
>>> ds = ETCI(split='test')
>>> fig = ds.plot(ds[4])
>>> plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/12021217/158070039-f2f29c9d-b5e5-4022-b7ab-d72fdfaf68cd.png)

**Comment by calebrob6** [comment]
I think this is just an issue with the dataset. If you open up `ds.files[4]` you can see that the `vv` and `vh` PNGs are indeed mostly empty. Also, different images are plotted fine:

![image](https://user-images.githubusercontent.com/1088078/158073498-a7bf6f4a-d78b-4ba4-a21c-8a3fa3b826eb.png)

**Comment by calebrob6** [comment]
See FAQ here https://nasa-impact.github.io/etci2021/
