### ISSUE TITLE
FCSiam tests require internet access

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#495]
The FCSiam tests have been intermittently failing in CI when an SSL certificate is expired or a runner loses internet connection. @calebrob6 can you work your magic on this like you did in #265? I'm guessing this was introduced during the refactor in #345.

### Steps to Reproduce

1. Turn off WiFi on your laptop
2. Run `pytest tests/models/test_fcsiam.py`

I confirmed that only `test_fcsiam.py` is affected, no other datasets or models require internet access.

P.S. The file it's trying to download is https://download.pytorch.org/models/resnet34-333f7ec4.pth if that helps narrow it down.

**Comment by isaaccorley** [comment]
I think all that needs to be changed is that we pass encoder_weights=None to the models in the tests. I'll make a quick PR for this.
