### ISSUE TITLE
datasets.SEN12MS - dB values are cast to int32

### ISSUE THREAD

**Issue by khdlr** [microsoft/torchgeo#500]
When loading samples from the SEN12MS dataset, the Sentinel-1 dB values (floats ranging from around -30 to 0) are cast to int32, discarding a lot of important information. 

[This line](https://github.com/microsoft/torchgeo/blob/main/torchgeo/datasets/sen12ms.py#L269) seems to be the culprit.

Fixing this would require either breaking the current behaviour where S1 and S2 imagery are stacked into a single tensor, or casting everything to float32 (not sure if this is okay for S2 data)

**Comment by adamjstewart** [comment]
I vote for casting everything to float32. I think PyTorch will automatically do this for us, so all you have to do is remove the cast to int32. Want to open a PR?

**Comment by khdlr** [comment]
Sure, I'm happy to open a PR :blush: 

I believe the reason for the cast is that the Sentinel-2 imagery comes as `uint16` data, which is not a thing in torch. In general, the geo-tiffs have the following datatypes:

```
Sentinel-1: float32
Sentinel-2: uint16
Label:      uint8
```

My current workaround is to just cast the `uint16` to `int32` and leave the others as they are. As you said, PyTorch will automatically cast the result to float32 when stacking.

Also not sure about the labels – but I don't believe having them as int32 is that useful.
