### ISSUE TITLE
Error loading Esri2020 data set from torchgeo main branch.

### ISSUE THREAD

**Issue by tinkueg** [microsoft/torchgeo#503]
It seems that **Esri2020** data set was removed from **torchgeo 0.2.1 release**. You could have put this information in the release notes! The documentation [https://torchgeo.readthedocs.io/en/latest/api/datasets.html#esri2020](url) still exists! I wasted my time to figure this.

I reuest to kindly put such information in the release notes.

Thanks!
MKG

**Comment by isaaccorley** [comment]
The release notes state that v0.2.1 is a bug fix release. Esri2020 was added after v0.2.0 so it won't be added to our stable version until v0.3.0. For now it is only available in the latest version which is the version of the docs you're looking at. Here are the [docs](https://torchgeo.readthedocs.io/en/v0.2.1/api/datasets.html#geospatial-datasets) for v0.2.1.

**Comment by calebrob6** [comment]
@tinkueg you can do `pip install git+https://github.com/microsoft/torchgeo.git` to install the `main` branch which has Esri2020.

**Comment by tinkueg** [comment]
Hi! Thanks for the reply!

I was not expecting a documentation for an unreleased version..but now I followed the suggested method and I get a new error while loading the dataset. This was working in my previous installation a couple of week back.

Any suggestions? It was working in my previous installation but it does't work now for some reason.

(torchgeo_env) user: $ python train.py
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    dataset = Esri2020(root='./../data/', transforms=None, cache=True, download=False, checksum=False)
  File "/home/manish/projects/pytorch/torchgeo_lcc/torchgeo_env/lib/python3.8/site-packages/torchgeo/datasets/esri2020.py", line 101, in __init__
    super().__init__(root, crs, res, transforms, cache)
  File "/home/manish/projects/pytorch/torchgeo_lcc/torchgeo_env/lib/python3.8/site-packages/torchgeo/datasets/geo.py", line 357, in __init__
    with WarpedVRT(src, crs=crs) as vrt:
  File "rasterio/_warp.pyx", line 1072, in rasterio._warp.WarpedVRTReaderBase.__init__
  File "rasterio/_err.pyx", line 216, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_AppDefinedError: Too many points (4624 out of 4624) failed to transform, unable to compute output bounds.

**Comment by adamjstewart** [comment]
@nilsleh wrote the Esri2020 dataset, can you take a look at this error message?

**Comment by nilsleh** [comment]
> @nilsleh wrote the Esri2020 dataset, can you take a look at this error message?

I am not encountering the error. The following works fine for me and `print(torchgeo.__version__)` yields `0.3.0.dev0`.
```
ds = Esri2020("./data/esri", transforms=None, cache=True, download=False, checksum=False)
sampler = RandomGeoSampler(ds, size=256, length=1000)
dl = DataLoader(ds, sampler=sampler, batch_size=10, collate_fn=stack_samples)
for sample in dl:
    print(sample["mask"].shape)
```

**Comment by calebrob6** [comment]
@tinkueg, were you able to resolve this?

**Comment by adamjstewart** [comment]
No response from original reported and we're unable to reproduce this, closing. Let us know if you are still able to reproduce this and we'll take a look.
