### ISSUE TITLE
Working with samplers 

### ISSUE THREAD

**Issue by kethan52** [microsoft/torchgeo#520]
How to create the two data loaders from taking data from the same samplers without overwritting each other ?

**Comment by adamjstewart** [comment]
I think this depends on what you're trying to do. I assume you're talking about GeoDatasets and GeoSamplers? You'll likely want to combine both Datasets into a single Dataset before creating your DataLoader. For example, if you want to index from both `dataset1` and `dataset2` at the same time, and only want to sample from regions where both datasets actually have data, then you'll create `dataset3 = dataset1 & dataset2`. Here `&` means "compute the spatiotemporal intersection of these two datasets and return a single dataset". There are other ways to do this, but `IntersectionDataset` is probably the easiest solution. Unless I'm completely misunderstanding what you're trying to do.

**Comment by kethan52** [comment]
Okay Thank you soo much!!
