### ISSUE TITLE
Public access to NAIP data through URL in tutorial is broken

### ISSUE THREAD

**Issue by remtav** [microsoft/torchgeo#526]
It's not currently possible to download NAIP tiles in "getting started" tutorial [in this cell](https://torchgeo.readthedocs.io/en/latest/tutorials/getting_started.html#Datasets).

**Comment by calebrob6** [comment]
Can you replace the URLs with ones that start with "https://naipeuwest.blob.core.windows.net/"

**Comment by adamjstewart** [comment]
This seems to work! Let me open a PR.
