### ISSUE TITLE
Augmentation library options

### ISSUE THREAD

**Issue by calebrob6** [microsoft/torchgeo#53]
The following libraries provide APIs for performing augmentations:
- [albumentations](https://albumentations.ai/docs/)
  - Dependencies on opencv-python-headless, scikit-image, numpy, scipy, PyYAML
  - Looks to be CPU only
  - Looks to support >3 channels where possible
- [kornia](https://kornia.readthedocs.io/en/latest/)
  - Only dependency is pytorch
  - GPU enabled
  - Supports >3 channels where possible
- [imgaug](https://imgaug.readthedocs.io/en/latest/index.html)
  - TODO

**Comment by adamjstewart** [comment]
@calebrob6 @isaaccorley is it safe to say that we've decided on Kornia?

**Comment by isaaccorley** [comment]
+1 for kornia

**Comment by calebrob6** [comment]
I'm agreed
