### ISSUE TITLE
Can't able to iterate through the dataloader 

### ISSUE THREAD

**Issue by kethan52** [microsoft/torchgeo#534]
i want to divide the custom dataset into train and test so I used the following 

```python
class CustomDataset(RasterDataset):
  filename_glob = ".tif"

  def __getitem__(self, query):
    a_max = -0.2
    data=super().__getitem__(query)
    data["mask"]=transform(data)["image"][8,:,:]
    data["mask"]=data["mask"].reshape([1024,1024])
    data["mask"]=torch.where(
        data["mask"]>=a_max,
        torch.ones_like(data["mask"]),
        torch.zeros_like(data["mask"])
    )
    data["image"]=data["image"][0:8,:,:]
    data["mask"]=data["mask"].long()
    del data["bbox"]
    return data

sampler = RandomGeoSampler(ds, size=307.2, length=20,roi=None)
train_size = int(0.8 * len(sampler))
test_size = len(sampler) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(sampler, [train_size, test_size])
dl = DataLoader(ds, sampler=train_dataset, collate_fn=stack_samples)
val_dl = DataLoader(ds, sampler=test_dataset, collate_fn=stack_samples)

model =SemanticSegmentationTask(
    segmentation_model="fcn",
    encoder_name="resnet50",
    encoder_weights=None,
    in_channels=8,
    num_classes=2,
    num_filters=64,
    loss="jaccard",
    ignore_zeros=False,
    learning_rate=0.1,
    learning_rate_schedule_patience=10,
)

trainer = pl.Trainer(
                  gpus=1,
                  callbacks=[checkpoint_callback, early_stopping_callback],
                  logger=[csv_logger],
                  min_epochs=10,
                  max_epochs=50,
                  log_every_n_steps=10,
               )

trainer.fit(model,dl,val_dl)
```
------------------------------------------------------------------------------------------------------------
![Screenshot (1444)](https://user-images.githubusercontent.com/41123619/167804679-ce8f90d5-abef-4beb-b8cb-bff3258c2dda.png)
-

**Comment by adamjstewart** [comment]
There are a few things wrong with this code:

1. `filename_glob` should be `*.tif`, not `.tif`
2. `torch.utils.data.random_split` takes in a `Dataset`, not a `Sampler`
3. `torch.utils.data.random_split` only works for datasets indexed by integer, our `GeoDataset` class is indexed by a `BoundingBox`

The correct way to divide a `GeoDataset` into train-val-test splits is to use the `roi` parameter. This ensures that you have non-overlapping regions. We could implement some kind of `geo_random_split` method that splits by image, but then you run the risk of having two images with overlapping spatial coverage in both train and test.

**Comment by adamjstewart** [comment]
@kethan52 does the above comment solve your issues?

**Comment by kethan52** [comment]
Sorry @adamjstewart i can able to solve the issue
