### ISSUE TITLE
Fine tune the trainer 

### ISSUE THREAD

**Issue by kethan52** [microsoft/torchgeo#541]
Hi, I want to fine-tune the trainer like fitting the same trainer for 2 times and what to see the increase of result is it possible to fit the same trainer for 2 times ??. if possible can I get the snippet

**Comment by calebrob6** [comment]
Hi @kethan52, if you look at the tutorial here https://torchgeo.readthedocs.io/en/latest/tutorials/trainers.html, you should be able to run `trainer.fit(model=task, datamodule=datamodule)` (cell 8) twice.
