### ISSUE TITLE
GOES datasets

### ISSUE THREAD

**Issue by ngam** [microsoft/torchgeo#546]
Hello team, I was wondering if there were any GOES datasets in the pipelines or if there was sufficient interest in coming up with some. Adding some GOES datasets here could be a nice addition (maybe?!)

I could potentially curate one from my own research later in the summer

**Comment by adamjstewart** [comment]
Would love to have a GOES dataset! I won't have time to work on this any time soon, but if you submit a PR I can review it. See any recent dataset PR to get an idea of which files need to be updated/where to add tests.

**Comment by mariajmolina** [comment]
Hello! Have there been any updates on the GOES dataset front?

**Comment by adamjstewart** [comment]
I haven't seen anything. If you want to try to write one yourself, you could follow [this tutorial](https://torchgeo.readthedocs.io/en/stable/tutorials/custom_raster_dataset.html). Ideally you could also contribute it back to TorchGeo, which requires a bit of additional documentation and unit tests. See [here](https://torchgeo.readthedocs.io/en/stable/user/contributing.html#datasets) for the full list of requirements.
