### ISSUE TITLE
Dataset plotting

### ISSUE THREAD

**Issue by calebrob6** [microsoft/torchgeo#587]
Some of our datasets (idtrees?) are plotting (H, W, 1) images, can we just squash these so we can support older versions of matplotlib?

**Comment by isaaccorley** [comment]
I'm guessing this is regarding the idtrees CHM data which gets plotted with a colormap? If it works then we should squeeze the singleton dim.

**Comment by isaaccorley** [comment]
Looks like we didn't squeeze the singleton dimension for the CHM data when plotting. It looks like it would only be a one line change. Is this something you want to do so we can revert the matplotlib version change that was made?

**Comment by adamjstewart** [comment]
If it's that easy might as well try it and see if it works. Can't remember if there were other datasets that required this.

**Comment by adamjstewart** [comment]
I think we can close this, I'm not worried about supporting ancient matplotlib.
