### ISSUE TITLE
VectorDataset incorrect sample shape 

### ISSUE THREAD

**Issue by TCherici** [microsoft/torchgeo#674]
### Description

Querying a sample from a VectorDataset object returns (sometimes?) a mask with incorrect shape.

This is caused by not rounding the calculated width and height pixel values to the nearest integer, and just taking the `int(width)` and `int(height)` values instead for `masks = rasterio.features.rasterize` in [torchgeo.datasets.geo.py:614](https://github.com/microsoft/torchgeo/blob/b41b6d68f99edfbe4d82b31f6f9b16cbd33f485e/torchgeo/datasets/geo.py#L614).

### Steps to reproduce

Run the following code to reproduce the error:
```
from torchgeo.datasets import CanadianBuildingFootprints
from torchgeo.samplers import RandomGeoSampler

cbf_dataset = CanadianBuildingFootprints(download=True)  # or any other VectorDataset-based dataset

size = 512

sampler = RandomGeoSampler(cbf_dataset, size=size, length=100)  # or any other sampler
query = next(iter(sampler))

sample = cbf_dataset[query]

print(sample["mask"].shape)
assert sample["mask"].shape[0] == size, sample["mask"].shape
assert sample["mask"].shape[1] == size, sample["mask"].shape
```

### Version

0.3.0

**Comment by adamjstewart** [comment]
Yes, the recommended way to submit PRs is to create a branch on your own fork, see https://torchgeo.readthedocs.io/en/stable/user/contributing.html#git.

I'll take a look at your PR, thanks for catching this bug!

**Comment by adamjstewart** [comment]
I'm able to reproduce this locally. I also managed to reproduce the intermittent nature of this bug by running in a for loop:
```
torch.Size([511, 512])
torch.Size([511, 512])
torch.Size([512, 512])
torch.Size([511, 511])
torch.Size([511, 512])
torch.Size([512, 512])
torch.Size([511, 512])
torch.Size([512, 512])
torch.Size([511, 512])
torch.Size([512, 512])
torch.Size([512, 512])
torch.Size([512, 512])
torch.Size([511, 511])
```
Will test your fix now.
