### ISSUE TITLE
Trainers tutorial fails without refresh

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#765]
### Description

If you run the Trainers tutorial in Google Colab, it crashes with an import error. https://issuehint.com/issue/Lightning-AI/lightning-flash/1424#131142861 suggests that this is a pip installation issue.

### Steps to reproduce

Run the tutorial in Google Colab. The imports cell fails with the following error message:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-51de89d93fc2>](https://localhost:8080/#) in <module>
     10 from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint
     11 from pytorch_lightning.loggers import CSVLogger
---> 12 from torchgeo.datamodules import CycloneDataModule
     13 from torchgeo.trainers import RegressionTask

7 frames
[/usr/local/lib/python3.7/dist-packages/PIL/ImageFont.py](https://localhost:8080/#) in <module>
     35 from . import Image
     36 from ._deprecate import deprecate
---> 37 from ._util import is_directory, is_path
     38 
     39 

ImportError: cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.7/dist-packages/PIL/_util.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

### Version

releases/v0.3

**Comment by calebrob6** [comment]
This is solved by simply restarting the colab runtime. `%pip install torchgeo[datasets]` uninstalls whatever version of PIL is pre-installed and there is a clear notification that you must restart the runtime for the changes to take effect.

**Comment by adamjstewart** [comment]
Yeah, that's what I determined as well. Is there any way around this? I wish Colab didn't import things for me...

**Comment by adamjstewart** [comment]
I also wish pip would take into account packages that were already installed instead of updating everything and breaking the environment...

**Comment by calebrob6** [comment]
I have no idea, but let's close as this isn't a torchgeo issue.

**Comment by adamjstewart** [comment]
Haven't given up on this just yet: https://github.com/Lightning-AI/lightning/issues/17136

**Comment by adamjstewart** [comment]
Fixed by https://github.com/googlecolab/colabtools/issues/3514 and https://github.com/Lightning-AI/lightning/pull/17156
