### ISSUE TITLE
summarywriter on each process?

### ISSUE THREAD

**Issue by austinmw** [microsoft/torchgeo#824]
### Description

It looks like [figures are being drawn to TensorBoard on every process](https://github.com/microsoft/torchgeo/blob/7306a57f8827ea378008497d94e4020de0e91423/torchgeo/trainers/detection.py#L176). I could be wrong, but would it be better in the multi-gpu/multi-node case to only draw on the rank zero process using `pytorch_lightning.utilities.distributed.rank_zero_only`?

### Steps to reproduce

I was looking into why validation was slow and noticed the plotting portion. Though this probably wouldn't speed anything up, I wonder if each process is trying to overwrite eachother's TB logs. Could be missing something though!

### Version

0.4.0.dev0

**Comment by austinmw** [comment]
Sure can do. Double checking with Lightning team to make sure this isn't unnecessary.

**Comment by austinmw** [comment]
Turns out I was wrong about this! 

Adrian Wälchli: "It's taken care of by Lightning already. If you use self.log or like you show above, tainer.logger.experiment, it won't log on rank > 0. We consider this boilerplate, and thus handle it for the user."

**Comment by adamjstewart** [comment]
Wait, is that actually true? Looking at the documentation of [`LightningModule.log`](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_module.html#log), there's a `rank_zero_only` parameter which is False by default. Would have to check `LightningModule.logger.experiment.add_figure` but I couldn't quickly find the docs on this.

**Comment by austinmw** [comment]
I think because of this: https://github.com/Lightning-AI/lightning/blob/4eb7766f3c222b95216f5e2831894a5143f70882/src/pytorch_lightning/loggers/tensorboard.py#L157-L158
And https://github.com/Lightning-AI/lightning/blob/4eb7766f3c222b95216f5e2831894a5143f70882/src/pytorch_lightning/loggers/logger.py#L34
returning a DummyExperiment
