### ISSUE TITLE
RasterDataset with separate_files and length of dataset

### ISSUE THREAD

**Issue by nilsleh** [microsoft/torchgeo#873]
### Description

I have a custom `RasterDataset` and I think the combination of `RasterDataset` with `separate_files=True` and getting the length of the instantiated `RasterDataset` yields a "wrong" or unexpected result, because `GeoDataset` specifies the length of the dataset as the length of `self.index`. However, if `separate_files=True` then each separate multispectral band of a single sample increases the index by the amount of bands, while technically it is still just one sample. So if I have a single Sentinel2 image with separate files for each band and load a custom dataset then `len(ds)` yields 13 even though I would expect 1.

### Steps to reproduce

Currently, Landsat and Sentinel are implemented datasets with `separate_files=True`, so I think it could be reproduced on that.
```python
from torchgeo.datasets import Sentinel2

ds = Sentinel2("/path/to/dir")
print(len(ds))
```

### Version

'0.4.0.dev0'

**Comment by nilsleh** [comment]
Ah I see, sorry should have checked that. Now I also get why in the Custom RasterDataset tutorial the `filename_glob` is only looking for the `B02` band. Thanks.

**Comment by adamjstewart** [comment]
No worries. This is a common mistake, which means it's likely a poor design. Something to refactor if we ever move to torchdata.
