### ISSUE TITLE
ChesapeakeCVPRDataModule assert prior labels 

### ISSUE THREAD

**Issue by daniel-furman** [microsoft/torchgeo#889]
### Description

In the ChesapeakeCVPR(GeoDataset) class, there's one assertion surrounding a prior from cooccurrences, the second to last file in the dataset integrity list, "wv_1m_2014_extended-debuffered-val_tiles/m_3708035_ne_17_1_prior_from_cooccurrences_101_31_no_osm_no_buildings.tif". However, this file does not come with the zipped data as downloaded from the link below. I had to comment it out, and then the code worked correctly. 

I believe you'd want to delete this one file from the list so that other people's code doesn't fail. 

### Steps to reproduce

1. Download the CVPR dataset from this link: https://lila.science/datasets/chesapeakelandcover
2. Execute the following code to reproduce:

### Version

0.3.1

```from torchgeo.datamodules import ChesapeakeCVPRDataModule

d_mod = ChesapeakeCVPRDataModule(root_dir='...',
                    train_splits=[f"{state}-train"],
                    val_splits=[f"{state}-val"],
                    test_splits=[f"{state}-test"],
                    patches_per_tile=200,
                    patch_size=128,
                    batch_size=64,
                    num_workers=0, 
                    class_set=7,
                    seed=1337,)

d_mod.prepare_data()
d_mod.setup(stage=None)
val = d_mod.val_dataloader()
train = d_mod.train_dataloader()

**Comment by calebrob6** [comment]
Hi @daniel-furman, you can download the prior extension data from https://zenodo.org/record/5866525/. The dataset object should auto download this -- https://github.com/microsoft/torchgeo/blob/main/torchgeo/datasets/chesapeake.py#L428. Let me know if this isn't working!

**Comment by daniel-furman** [comment]
Hi @calebrob6, the download through torchgeo was erring after about half an hour. By comparison, the azcopy command I used on to get the data as recommended by the Lila science link above worked and ran quickly. 

Either way, I was able to get the data module to work by commenting out the prior label assert.

**Comment by calebrob6** [comment]
Yep, `azcopy` is definitely the recommended way to download this.
