### ISSUE TITLE
Using VHR10 dataset with AugmentationSequential

### ISSUE THREAD

**Issue by AVTsoof** [microsoft/torchgeo#894]
https://github.com/microsoft/torchgeo/blob/0c7d46be10c47fdb370364fddb7328d1b0661ac2/torchgeo/datasets/nwpu.py#L143

sample (dict) has the key: `'label'`, but should have the key `'mask'`

The reason:

If using torchgeo augmentations
https://github.com/microsoft/torchgeo/blob/main/torchgeo/transforms/transforms.py#L40

The parameter `data_keys` in `kornia.augmentation.AugmentationSequential` accepts only `[“input”, “mask”, “bbox”, “bbox_xyxy”, “bbox_xywh”, “keypoints”]` as stated in [kornia doc](https://kornia.readthedocs.io/en/latest/augmentation.container.html#augmentation-sequential)

**Comment by ashnair1** [comment]
#847 will address this issue along with adding a plot method.
