### ISSUE TITLE
DataModules: skip prepare_data

### ISSUE THREAD

**Issue by adamjstewart** [microsoft/torchgeo#967]
### Summary

We should skip the `prepare_data` step in our data modules unless downloading is actually required.

### Rationale

Instantiating the dataset is slow. Currently, all of our datamodules instantiate the dataset at least twice on the off chance that someone is requesting the dataset to be downloaded. This isn't needed most of the time.

### Implementation

A better solution would be to replace:
```python
def prepare_data(self) -> None:
    Dataset(**self.kwargs)
```
with this:
```python
def prepare_data(self) -> None:
    if self.kwargs.get("download", False):
        Dataset(**self.kwargs)
```
in all of our data modules.

**Comment by iamhbc** [comment]
The solution is to replace the prepare_data() method with the code above in all of our data modules. This code will check the "download" keyword argument and only download the dataset if it is set to true. This will significantly reduce the time required to instantiate the dataset and speed up our data modules.
